import os

CHECK_PTY_FLAG_VAR = "TenzirCLOUD_CHECK_PTY"
CHECK_PTY = CHECK_PTY_FLAG_VAR in os.environ

NO_PTY_FLAG_VAR = "TenzirCLOUD_NO_PTY"
NO_PTY = NO_PTY_FLAG_VAR in os.environ

TRACE_FLAG_VAR = "TenzirCLOUD_TRACE"
TRACE = TRACE_FLAG_VAR in os.environ
