FROM ubuntu:18.04
LABEL maintainer="engineering@tenzir.com"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && apt-get -qq install -y libc++1 libc++abi1 libpcap0.8 \
  openssl libatomic1 python3 python3-pip jq tcpdump rsync

RUN pip3 install --upgrade pip && pip install --upgrade cmake && \
  cmake --version

COPY opt/vast /opt/vast

RUN rsync -avh /opt/vast/* /usr/local
RUN ls -lah /usr/local

RUN echo "Adding tenzir user" && \
  groupadd --gid 20097 tenzir && useradd --system --uid 20097 --gid tenzir tenzir

EXPOSE 42000/tcp
WORKDIR /data
RUN chown -R tenzir:tenzir /data
VOLUME ["/data"]

USER tenzir:tenzir
ENTRYPOINT ["/usr/local/bin/vast"]
CMD ["--help"]
