FROM ubuntu:20.04
LABEL maintainer="engineering@tenzir.com"
ENV DEBIAN_FRONTEND noninteractive
ENV PREFIX /usr/local

RUN apt-get -qq update && apt-get -qq install -y libasan5 libc++1 libc++abi1 \
  libpcap0.8 openssl lsb-release python3 python3-pip jq tcpdump rsync wget \
  libflatbuffers-dev libyaml-cpp-dev libspdlog-dev
# Install Apache Arrow (c.f. https://arrow.apache.org/install/)
# TODO: Revert the commit that introduced this version pinning once ch20162
# is done and we can use latest upstream again.
RUN wget https://apache.bintray.com/arrow/ubuntu/pool/focal/main/a/apache-arrow-archive-keyring/apache-arrow-archive-keyring_1.0.1-1_all.deb && \
  apt-get -qqy install ./apache-arrow-archive-keyring_1.0.1-1_all.deb && \
  apt-get -qq update && \
  apt-get -qqy install libarrow-dev=1.0.1-1

RUN pip3 install --upgrade pip && pip install --upgrade cmake && \
  cmake --version

COPY opt/vast /opt/vast
RUN rsync -avh /opt/vast/* $PREFIX
EXPOSE 42000/tcp

RUN echo "Adding vast user" && useradd --system --user-group vast

RUN mkdir -p /etc/vast /var/log/vast /var/lib/vast
COPY systemd/vast.yaml /etc/vast/vast.yaml
RUN chown -R vast:vast /var/log/vast /var/lib/vast

WORKDIR /var/lib/vast
VOLUME ["/var/lib/vast"]

USER vast:vast
ENTRYPOINT ["vast"]
CMD ["--help"]
