FROM ubuntu:18.04
LABEL maintainer="engineering@tenzir.com"
ENV DEBIAN_FRONTEND noninteractive
ENV PREFIX /usr/local

RUN apt-get -qq update && apt-get -qq install -y libasan5 libc++1 libc++abi1 \
  libpcap0.8 openssl lsb-release python3 python3-pip jq tcpdump rsync wget
# Install Apache Arrow (c.f. https://arrow.apache.org/install/)
RUN wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb && \
  apt-get -qqy install ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb && \
  apt-get -qq update && \
  apt-get -qqy install libarrow-dev

# Install flatbuffers
RUN pushd $(mktemp)
RUN curl -LO https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz
RUN tar xzf v1.12.0.tar.gz
RUN cd flatbuffers-1.12.0
RUN cmake -B build-dir \
  -DFLATBUFFERS_BUILD_TESTS=OFF \
  -DFLATBUFFERS_BUILD_GRPCTEST=OFF
RUN cmake --build build-dir --target all --parallel
RUN sudo cmake --build build-dir --target install
RUN popd

RUN pip3 install --upgrade pip && pip install --upgrade cmake && \
  cmake --version

COPY opt/vast /opt/vast
RUN rsync -avh /opt/vast/* $PREFIX
EXPOSE 42000/tcp

RUN echo "Adding vast user" && useradd --system --user-group vast

RUN mkdir -p /etc/vast /var/log/vast /var/db/vast
COPY systemd/vast.conf /etc/vast/vast.conf
RUN chown -R vast:vast /var/log/vast /var/db/vast

WORKDIR /var/db/vast
VOLUME ["/var/db/vast"]

USER vast:vast
ENTRYPOINT ["vast"]
CMD ["--help"]
