# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, stdenv, nodejs, git, cacert, fetchurl, writeShellScript, writeShellScriptBin }:
{ src, overrideAttrs ? null, ... } @ args:

let

  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Simple stub that provides the global yarn command.
  yarn = writeShellScriptBin "yarn" ''
    exec '${nodejs}/bin/node' '${./.yarn/releases/yarn-3.3.0.cjs}' "$@"
  '';

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs yarn ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
  };

  # Comman variables that we set in a Nix build, but not in a Nix shell.
  buildVars = ''
    # Make Yarn produce friendlier logging for automated builds.
    export CI=1
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    export npm_config_build_from_source=true
    # Disable Nixify plugin to save on some unnecessary processing.
    export yarn_enable_nixify=false
  '';

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = writeShellScript "yarn-cache-builder" ''
      source $stdenv/setup
      cd "$src"
      ${buildVars}
      HOME="$TMP" yarn_cache_folder="$TMP" \
        yarn nixify fetch-one $locator
      # Because we change the cache dir, Yarn may generate a different name.
      mv "$TMP/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit src builder locator;
    name = lib.strings.sanitizeDerivationName locator;
    buildInputs = [ yarn git cacert ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeShellScript "collect-yarn-cache" (lib.concatMapStrings (drv: ''
      cp ${drv} '${drv.outputFilename}'
    '') drvs);


  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "vast-frontend";

    configurePhase = ''
      ${buildVars}

      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure



      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p "$out/libexec/$name" "$out/bin"

      # Move the package contents to the output directory.
      # - If the package.json has a `files` field, only files matching those patterns are copied
      # - Otherwise all files are copied
      yarn pack --out package.tgz
      tar xzvf package.tgz --directory "$out/libexec/$name" --strip-components=1

      cp .yarnrc* 'yarn.lock' "$out/libexec/$name"
      cp --recursive .yarn "$out/libexec/$name"

      # If the project uses the node-modules linker, then
      # include the node_modules folder in the package.
      if [ -d node_modules ]; then
        cp --recursive node_modules "$out/libexec/$name"
      else
        # Otherwise, assume PnP. Copy the loader into the package.
        cp .pnp.* "$out/libexec/$name"
      fi

      cd "$out/libexec/$name"

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $out/bin

      # A package with node_modules doesn't need the cache
      if [ -d node_modules ]; then
        yarn cache clean
      fi

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
      yarn-freestanding = yarn;
      yarn = writeShellScriptBin "yarn" ''
        exec '${yarn}/bin/yarn' --cwd '${project}/libexec/${project.name}' "$@"
      '';
    };
  });

cacheEntries = {
"@ampproject/remapping@npm:2.2.0" = { filename = "@ampproject-remapping-npm-2.2.0-114878fa50-d74d170d06.zip"; sha512 = "d74d170d06468913921d72430259424b7e4c826b5a7d39ff839a29d547efb97dc577caa8ba3fb5cf023624e9af9d09651afc3d4112a45e2050328abc9b3a2292"; };
"@antfu/install-pkg@npm:0.1.1" = { filename = "@antfu-install-pkg-npm-0.1.1-2770194765-a463af6a0d.zip"; sha512 = "a463af6a0df3cf0769fd88ec94d135ca54e4f7329422fa3815bf1e71fb4ca510ec02bb39935bec65a15a8d8df5e76bf8e6a7df0c7c6cc512aefa3bec85ad903f"; };
"@antfu/utils@npm:0.5.2" = { filename = "@antfu-utils-npm-0.5.2-8c99b8b224-9b91446b2d.zip"; sha512 = "9b91446b2dbb823abeeba1cc33d6ebf701a462923408ad4751fbe162da46ae0669c774c2b5435fc77691dc207ce5de5945e693d5163e07d6ef42e376b04c7af4"; };
"@esbuild/linux-x64@npm:0.16.7" = { filename = "@esbuild-linux-x64-npm-0.16.7-3bd2cb3ab5-8.zip"; sha512 = "24328c7b37dda602f9a0ef9e30615c1fd631156b54602b2cde79c8bb0f734acb22da71083b5ec2f7d19b7253d8b65de8f5c24802ff83deab6c2223bbc57ecbb1"; };
"@eslint/eslintrc@npm:1.3.3" = { filename = "@eslint-eslintrc-npm-1.3.3-9e3a462140-f03e9d6727.zip"; sha512 = "f03e9d6727efd3e0719da2051ea80c0c73d20e28c171121527dbb868cd34232ca9c1d0525a66e517a404afea26624b1e47895b6a92474678418c2f50c9566694"; };
"@fontsource/fira-mono@npm:4.5.10" = { filename = "@fontsource-fira-mono-npm-4.5.10-4c99c6554e-0bf058ff1d.zip"; sha512 = "0bf058ff1d6f4dcd0bedb4d459ed21124ffd93b7ca1c540068f98057fd7cf96320c69126e88caf1bc5e318c920d9157a2b0b30fd0835573ea6808ffa63c16fad"; };
"@gar/promisify@npm:1.1.3" = { filename = "@gar-promisify-npm-1.1.3-ac1a325862-4059f790e2.zip"; sha512 = "4059f790e2d07bf3c3ff3e0fec0daa8144fe35c1f6e0111c9921bd32106adaa97a4ab096ad7dab1e28ee6a9060083c4d1a4ada42a7f5f3f7a96b8812e2b757c1"; };
"@humanwhocodes/config-array@npm:0.11.8" = { filename = "@humanwhocodes-config-array-npm-0.11.8-7955bfecc2-0fd6b3c54f.zip"; sha512 = "0fd6b3c54f1674ce0a224df09b9c2f9846d20b9e54fabae1281ecfc04f2e6ad69bf19e1d6af6a28f88e8aa3990168b6cb9e1ef755868c3256a630605ec2cb1d3"; };
"@humanwhocodes/module-importer@npm:1.0.1" = { filename = "@humanwhocodes-module-importer-npm-1.0.1-9d07ed2e4a-0fd22007db.zip"; sha512 = "0fd22007db8034a2cdf2c764b140d37d9020bbfce8a49d3ec5c05290e77d4b0263b1b972b752df8c89e5eaa94073408f2b7d977aed131faf6cf396ebb5d7fb61"; };
"@humanwhocodes/object-schema@npm:1.2.1" = { filename = "@humanwhocodes-object-schema-npm-1.2.1-eb622b5d0e-a824a1ec31.zip"; sha512 = "a824a1ec31591231e4bad5787641f59e9633827d0a2eaae131a288d33c9ef0290bd16fda8da6f7c0fcb014147865d12118df10db57f27f41e20da92369fcb3f1"; };
"@iconify/json@npm:2.1.152" = { filename = "@iconify-json-npm-2.1.152-af03f68707-e8715a7d77.zip"; sha512 = "e8715a7d776ca04f33b8c91a28c6c03abe1d9cfdc0e184227046ba26f656561153aa1e3fb07c3667a5d88ef655032abfc4325f44799d62c9a59ae4b43fa32e5f"; };
"@iconify/types@npm:2.0.0" = { filename = "@iconify-types-npm-2.0.0-faa2398199-029f58542c.zip"; sha512 = "029f58542c160e9d4a746869cf2e475b603424d3adf3994c5cc8d0406c47e6e04a3b898b2707840c1c5b9bd5563a1660a34b110d89fce43923baca5222f4e597"; };
"@iconify/utils@npm:2.0.3" = { filename = "@iconify-utils-npm-2.0.3-d08d5b7d03-66a2369fb8.zip"; sha512 = "66a2369fb88ebc6ad0651a822ce96d3efd9431cd3217eda2b24827419da496e4c258ef5ed90da95373e80c8ecb4156cf4bc26e1e70532c391721fa26f939a9c1"; };
"@jridgewell/gen-mapping@npm:0.1.1" = { filename = "@jridgewell-gen-mapping-npm-0.1.1-3bad172ac6-3bcc21fe78.zip"; sha512 = "3bcc21fe786de6ffbf35c399a174faab05eb23ce6a03e8769569de28abbf4facc2db36a9ddb0150545ae23a8d35a7cf7237b2aa9e9356a7c626fb4698287d5cc"; };
"@jridgewell/resolve-uri@npm:3.1.0" = { filename = "@jridgewell-resolve-uri-npm-3.1.0-6ff2351e61-b5ceaaf9a1.zip"; sha512 = "b5ceaaf9a110fcb2780d1d8f8d4a0bfd216702f31c988d8042e5f8fbe353c55d9b0f55a1733afdc64806f8e79c485d2464680ac48a0d9fcadb9548ee6b81d267"; };
"@jridgewell/set-array@npm:1.1.2" = { filename = "@jridgewell-set-array-npm-1.1.2-45b82d7fb6-69a84d5980.zip"; sha512 = "69a84d5980385f396ff60a175f7177af0b8da4ddb81824cb7016a9ef914eee9806c72b6b65942003c63f7983d4f39a5c6c27185bbca88eb4690b62075602e28e"; };
"@jridgewell/sourcemap-codec@npm:1.4.14" = { filename = "@jridgewell-sourcemap-codec-npm-1.4.14-f5f0630788-61100637b6.zip"; sha512 = "61100637b6d173d3ba786a5dff019e1a74b1f394f323c1fee337ff390239f053b87266c7a948777f4b1ee68c01a8ad0ab61e5ff4abb5a012a0b091bec391ab97"; };
"@jridgewell/trace-mapping@npm:0.3.17" = { filename = "@jridgewell-trace-mapping-npm-0.3.17-57578fd48c-9d703b859c.zip"; sha512 = "9d703b859cff5cd83b7308fd457a431387db5db96bd781a63bf48e183418dd9d3d44e76b9e4ae13237f6abeeb25d739ec9215c1d5bfdd08f66f750a50074a339"; };
"@neoconfetti/svelte@npm:1.0.0" = { filename = "@neoconfetti-svelte-npm-1.0.0-b1f8864b22-9f2374fcb1.zip"; sha512 = "9f2374fcb1748b161319f0070cf4fbc83703c8e4958a2a2a7d8b4eb240305939454f85b9781ad7ed2e5c9db4b88db4377c5a1be40172aca641c642a8d6710445"; };
"@nodelib/fs.scandir@npm:2.1.5" = { filename = "@nodelib-fs.scandir-npm-2.1.5-89c67370dd-a970d595bd.zip"; sha512 = "a970d595bd23c66c880e0ef1817791432dbb7acbb8d44b7e7d0e7a22f4521260d4a83f7f9fd61d44fda4610105577f8f58a60718105fb38352baed612fd79e59"; };
"@nodelib/fs.stat@npm:2.0.5" = { filename = "@nodelib-fs.stat-npm-2.0.5-01f4dd3030-012480b5ca.zip"; sha512 = "012480b5ca9d97bff9261571dbbec7bbc6033f69cc92908bc1ecfad0792361a5a1994bc48674b9ef76419d056a03efadfce5a6cf6dbc0a36559571a7a483f6f0"; };
"@nodelib/fs.walk@npm:1.2.8" = { filename = "@nodelib-fs.walk-npm-1.2.8-b4a89da548-190c643f15.zip"; sha512 = "190c643f156d8f8f277bf2a6078af1ffde1fd43f498f187c2db24d35b4b4b5785c02c7dc52e356497b9a1b65b13edc996de08de0b961c32844364da02986dc53"; };
"@npmcli/fs@npm:2.1.2" = { filename = "@npmcli-fs-npm-2.1.2-08d434e77b-405074965e.zip"; sha512 = "405074965e72d4c9d728931b64d2d38e6ea12066d4fad651ac253d175e413c06fe4350970c783db0d749181da8fe49c42d3880bd1cbc12cd68e3a7964d820225"; };
"@npmcli/move-file@npm:2.0.1" = { filename = "@npmcli-move-file-npm-2.0.1-b593d8f741-52dc02259d.zip"; sha512 = "52dc02259d98da517fae4cb3a0a3850227bdae4939dda1980b788a7670636ca2b4a01b58df03dd5f65c1e3cb70c50fa8ce5762b582b3f499ec30ee5ce1fd9380"; };
"@polka/url@npm:1.0.0-next.21" = { filename = "@polka-url-npm-1.0.0-next.21-02342f3d90-c7654046d3.zip"; sha512 = "c7654046d38984257dd639eab3dc770d1b0340916097b2fac03ce5d23506ada684e05574a69b255c32ea6a144a957c8cd84264159b545fca031c772289d88788"; };
"@rgossiaux/svelte-headlessui@npm:1.0.2" = { filename = "@rgossiaux-svelte-headlessui-npm-1.0.2-0e4d0fa744-54c256923a.zip"; sha512 = "54c256923a29beaa70dd271332ca89fc7dd251cd53da42f12fa8ff73f1abf7c82a90266d50fd40442a476c74466908f2a77e3aa086f9ad1073bb46d167f04504"; };
"@rollup/pluginutils@npm:5.0.2" = { filename = "@rollup-pluginutils-npm-5.0.2-6aa9d0ddd4-edea15e543.zip"; sha512 = "edea15e543bebc7dcac3b0ac8bc7b8e8e6dbd46e2864dbe5dd28072de1fbd5b0e10d545a610c0edaa178e8a7ac432e2a2a52e547ece1308471412caba47db8ce"; };
"@sveltejs/adapter-static@npm:1.0.0" = { filename = "@sveltejs-adapter-static-npm-1.0.0-00469ffd1d-1b48a93189.zip"; sha512 = "1b48a93189f5bd4470092f55026bd1c297cd7d3fef34304c159ac3b3e695a3bd1cb851c1b239f56041bc0b93afd63e450098e531afe369173ac0d9df6e9863a1"; };
"@sveltejs/kit@npm:1.0.0" = { filename = "@sveltejs-kit-npm-1.0.0-6f6557bc14-0e67d82860.zip"; sha512 = "0e67d82860130d9629c4dfe19486a326837f2396c5f7cb455a6ed2f0859a2e3b3f2c6c638bf6e0a4743d63f4807cbded4e8701a864be477b87e8cf0ede28e479"; };
"@sveltejs/vite-plugin-svelte@npm:2.0.2" = { filename = "@sveltejs-vite-plugin-svelte-npm-2.0.2-ba0604b695-6a223da864.zip"; sha512 = "6a223da864d74c4e6ea05881ee0cf79db8390953df6d506b79d2c37a365fe291e5a5bb330dcfb5366b61ee3915544fd37db3e134865085981342bab392a6a991"; };
"@sveltestack/svelte-query@npm:1.6.0" = { filename = "@sveltestack-svelte-query-npm-1.6.0-776e8dcef1-b2f02a5f11.zip"; sha512 = "b2f02a5f11768a19ac65c864eb66e71480fec62aba8e7be58c354ed97ffe91ad79c8c306fed73b5f8f6f496091e129de5afeab6be370db881b621aed19fc83b6"; };
"@tootallnate/once@npm:2.0.0" = { filename = "@tootallnate-once-npm-2.0.0-e36cf4f140-ad87447820.zip"; sha512 = "ad87447820dd3f24825d2d947ebc03072b20a42bfc96cbafec16bff8bbda6c1a81fcb0be56d5b21968560c5359a0af4038a68ba150c3e1694fe4c109a063bed8"; };
"@types/cookie@npm:0.5.1" = { filename = "@types-cookie-npm-0.5.1-4b655a0ac0-9a8d60fc84.zip"; sha512 = "9a8d60fc84797122bc399d6bd330fe5780dc7aab032321de705049ea925339f74658bfa418de483a625d51858770efef58df633ff2e20f1bdf7fbd74a52847e2"; };
"@types/estree@npm:1.0.0" = { filename = "@types-estree-npm-1.0.0-eddde5b631-910d97fb70.zip"; sha512 = "910d97fb7092c6738d30a7430ae4786a38542023c6302b95d46f49420b797f21619cdde11fa92b338366268795884111c2eb10356e4bd2c8ad5b92941e9e6443"; };
"@types/json-schema@npm:7.0.11" = { filename = "@types-json-schema-npm-7.0.11-79462ae5ca-527bddfe62.zip"; sha512 = "527bddfe62db9012fccd7627794bd4c71beb77601861055d87e3ee464f2217c85fca7a4b56ae677478367bbd248dbde13553312b7d4dbc702a2f2bbf60c4018d"; };
"@types/node@npm:18.11.15" = { filename = "@types-node-npm-18.11.15-556d6408a5-cae8692a5c.zip"; sha512 = "cae8692a5cee0316f93ee0342237eb921f70c51afb37c661c711a925a4642654ae7e404c5a80899d481c0cfaff3a6891ef04bacd330a2e72734192bfc91dc2d8"; };
"@types/pug@npm:2.0.6" = { filename = "@types-pug-npm-2.0.6-445b1c16dc-e8d09c3ddc.zip"; sha512 = "e8d09c3ddc7e6b87050a16d73694518f259a8ed74a0ab79b81b847baf89d92d44959ed68199966ac6f4a218c715c9bb3e4c86c8800d4868a4a674f4b21d2f01d"; };
"@types/sass@npm:1.43.1" = { filename = "@types-sass-npm-1.43.1-6770eea7c0-19eb71acc4.zip"; sha512 = "19eb71acc4b0d7db2170732a51ad18a34007021f42069652a5be8a3e3a448a470d2f970b9e85f734d1896bf3a25e48fb5132b4a989c101eb5df21cc171d426c5"; };
"@types/semver@npm:7.3.13" = { filename = "@types-semver-npm-7.3.13-56212b60da-00c0724d54.zip"; sha512 = "00c0724d54757c2f4bc60b5032fe91cda6410e48689633d5f35ece8a0a66445e3e57fa1d6e07eb780f792e82ac542948ec4d0b76eb3484297b79bd18b8cf1cb0"; };
"@typescript-eslint/eslint-plugin@npm:5.46.1" = { filename = "@typescript-eslint-eslint-plugin-npm-5.46.1-fdc1628d8f-4ea4af5faa.zip"; sha512 = "4ea4af5faa5c509113d575bf6ea1f76989f253b4839bb98bcda28450be7fc8a87788169e822b0f6d739aee67e32e824440ef00cebc294d4212ffb3fed1f0756a"; };
"@typescript-eslint/parser@npm:5.46.1" = { filename = "@typescript-eslint-parser-npm-5.46.1-0f8fb6bd75-784fe3ae68.zip"; sha512 = "784fe3ae688da85784b271c10d1e0b807583f4c370e32aa7a09b2584d0f7b92316a93cccbd9458bdf08f169b220097a4b0456bc5f62a210607a13a5fae84c972"; };
"@typescript-eslint/scope-manager@npm:5.46.1" = { filename = "@typescript-eslint-scope-manager-npm-5.46.1-fa50526032-bf934603dc.zip"; sha512 = "bf934603dc9c7da71eb26f415d13018f2a96dbba193a773bc440a5c93828365f09bb3db9be55189dfbbace414c6c48d7fad246c0d9717dab4676d0d79d6d8676"; };
"@typescript-eslint/type-utils@npm:5.46.1" = { filename = "@typescript-eslint-type-utils-npm-5.46.1-9914b480bd-a47f1b73ac.zip"; sha512 = "a47f1b73ac773a7f33421a8e8f9bc6e047f55236e3257b2c9eaa04d18595ab6505129ffdab86685e9c3bef564091315a2347150cd6e61a511cc2160667458014"; };
"@typescript-eslint/types@npm:5.46.1" = { filename = "@typescript-eslint-types-npm-5.46.1-3b67baff5e-91143d3304.zip"; sha512 = "91143d3304b8c70d69d9c8e5b7428cce3a222eacfbeb99e592d278668bcf998760731deae064a76157b9a0fc4911fe3178aa24e4ea6fe2ba68dd37113834c924"; };
"@typescript-eslint/typescript-estree@npm:5.46.1" = { filename = "@typescript-eslint-typescript-estree-npm-5.46.1-046777a7ec-21499b927b.zip"; sha512 = "21499b927b4118cd51e841b2e1b7e55621135f923f461b75dc8ca8442de38a82da5a0232dce5229e0266b6fc12d70696e0e912fcf1483d4c44f02e4cad39ed98"; };
"@typescript-eslint/utils@npm:5.46.1" = { filename = "@typescript-eslint-utils-npm-5.46.1-2435456a3b-db9fd1dfb2.zip"; sha512 = "db9fd1dfb2390e66041f9529d564f38ccf74042de68e0e1e3d319ba4d02d7cd969d75dc056f938b98acab53ad7c1e36c68eabb15c0b2e2296b081652fa8d3820"; };
"@typescript-eslint/visitor-keys@npm:5.46.1" = { filename = "@typescript-eslint-visitor-keys-npm-5.46.1-1884413c6d-952cf20e29.zip"; sha512 = "952cf20e29a040e0820e52d6815097abf042ea8e1fd5d013c0a319284ea0e2e29e0ca9ef244717450a6eb9d32ebf7fa9ed91185675a27adc35c9ad070d561b7c"; };
"@unocss/astro@npm:0.47.6" = { filename = "@unocss-astro-npm-0.47.6-cbb5a8e38c-8d7adf4d81.zip"; sha512 = "8d7adf4d8188b3743bb336b4b71eed9ce9c588332f921585d3183ca50ab02f4ac5a12a0f9ea7fa3d081d4973177b08eabe1db2fb870ee22709b2273793665f16"; };
"@unocss/cli@npm:0.47.6" = { filename = "@unocss-cli-npm-0.47.6-99a4a6d0aa-c8e5e8e5e1.zip"; sha512 = "c8e5e8e5e188baaed01d5edf99a530d61d01060474e234ee90c67ae4a6121db70fc949f222fc7408075af27e1e290af35810121b718c0b745c0091402ac3be57"; };
"@unocss/config@npm:0.47.6" = { filename = "@unocss-config-npm-0.47.6-1b6b1e9ef6-5543bcdd1a.zip"; sha512 = "5543bcdd1a0dad9dfd076263c92ad686931b3af041392ca618cff791825323f7c73f705d122c94f5100fcdce4e37584bf407dd19d5a6de9177eb0e7934597723"; };
"@unocss/core@npm:0.47.6" = { filename = "@unocss-core-npm-0.47.6-435dfb7e57-cbd02530fb.zip"; sha512 = "cbd02530fb4597081be8c306806c8e30fdde62d101ebc4fa4c15f17d21acae31ff6cc20503a4e854f581cd048efd5cad9aeb26326dfdd10326ca89eafa87bd07"; };
"@unocss/inspector@npm:0.47.6" = { filename = "@unocss-inspector-npm-0.47.6-adaae896c7-876edb3aa4.zip"; sha512 = "876edb3aa445b8b91b7ddd3bcde1604acdf54459d6eb42df4c79e30acf692440da3091c3a2666b168090bbb8dfc8f0f02b753b1107f8a6a16f34f1635f467645"; };
"@unocss/preset-attributify@npm:0.47.6" = { filename = "@unocss-preset-attributify-npm-0.47.6-fac1a1637b-902b01a57b.zip"; sha512 = "902b01a57b05265a13ad150fcdb30c45bf9fa646acf2d62011dcc3461dffaf92a9322c9f13a6347c02c0071101b3a03462affc5705021e03e890560cddeb6d22"; };
"@unocss/preset-icons@npm:0.47.6" = { filename = "@unocss-preset-icons-npm-0.47.6-4529c33055-5a894258b0.zip"; sha512 = "5a894258b04090806bf200437a89632a164de3ddef28e40cade047db7ed52e802c9a486b8b8acdee115e0554aa34ba09d3a44881a51fa40ad162d1563b76f25b"; };
"@unocss/preset-mini@npm:0.47.6" = { filename = "@unocss-preset-mini-npm-0.47.6-c0e1e924c6-0ece3d776f.zip"; sha512 = "0ece3d776f1ff5cfa9ad7119a21881aa39ba936a9751ae628c3df9dd62a6e0718116934795b12d493ddcf95b7211e35cca012b7fa8f0be36577216f704648d04"; };
"@unocss/preset-tagify@npm:0.47.6" = { filename = "@unocss-preset-tagify-npm-0.47.6-7830752036-2bdc86059d.zip"; sha512 = "2bdc86059d12c44b1a2fd2ed6460d9858bd9cea5118d1943b9ab6103751a66d8f6ee55379205e2c50bd20ebc9813c21edead1924150468f277483e4aa1418be9"; };
"@unocss/preset-typography@npm:0.47.6" = { filename = "@unocss-preset-typography-npm-0.47.6-4ca051890f-5cee0a1b9b.zip"; sha512 = "5cee0a1b9bd4cea68b2099211e8820ca48cb4c9abbff52837487991322306fb1f6328fbaf7c0105a99c07d2f3ef053ee4dd3c5da7402a0c82b18055f82e4d589"; };
"@unocss/preset-uno@npm:0.47.6" = { filename = "@unocss-preset-uno-npm-0.47.6-2305869db5-63adab596e.zip"; sha512 = "63adab596ea0998c15d9b75ac4bdfbdd600f3e7ac1f2df361b072032f8240bcfc5821cd9186451e72b37feb09d6043869e0d4edacceb50b0c804fbc5e43cefba"; };
"@unocss/preset-web-fonts@npm:0.47.6" = { filename = "@unocss-preset-web-fonts-npm-0.47.6-8e80c761d0-cc55b9bf82.zip"; sha512 = "cc55b9bf82ad859825404ba7db57138d239571f7fc14dcda5f4c6768ebf46369b0fc93d57d7761dda49943c408e95f5a85f54e2401b2e3db5664b0159c784f5d"; };
"@unocss/preset-wind@npm:0.47.6" = { filename = "@unocss-preset-wind-npm-0.47.6-8ae2a37b03-3ad3466c81.zip"; sha512 = "3ad3466c811bb4a188ed00271b2ebc72c9a11db12029d552547ffabe72d35038b0541573ae0882c3ceb5d0cbc9cffbda36861268d0bef46db2bb5f8ae4186313"; };
"@unocss/reset@npm:0.47.6" = { filename = "@unocss-reset-npm-0.47.6-50b2c2e87a-4ea2a48a62.zip"; sha512 = "4ea2a48a6274f51b339ebc034f05db6a1fe06be33c90c4a1915c55384960d6ec13150b3dd1504eca674f44f40b28c8854ca2ab361ae8485e8142ebaefeec5537"; };
"@unocss/scope@npm:0.47.6" = { filename = "@unocss-scope-npm-0.47.6-061e115953-4efd78cd95.zip"; sha512 = "4efd78cd955825b02f1a6130a72a1ccb6c45388f5116e839ad43fb0c4f32a041ab1100d93a11a2c7acb59818f3aa6629f757c026c0fa673a6584abb465691df8"; };
"@unocss/transformer-attributify-jsx@npm:0.47.6" = { filename = "@unocss-transformer-attributify-jsx-npm-0.47.6-e108869889-1289419292.zip"; sha512 = "12894192926e0fcc7d28ad5725acd4a25f53053fa956fce74848e50052ff1808b915a33680a1fd55279fe4c846d8ee208f76450e5eae21d5ab0154837eabd4b8"; };
"@unocss/transformer-compile-class@npm:0.47.6" = { filename = "@unocss-transformer-compile-class-npm-0.47.6-59b21c04bd-6ecc93f0b6.zip"; sha512 = "6ecc93f0b6494b916b08fb82d29c231553f92e3b36d0ac2d05563054b9344ff58f72912b35c050356672830be1a1bfc84c04a5346a0acc42fafa13a66e1645ac"; };
"@unocss/transformer-directives@npm:0.47.6" = { filename = "@unocss-transformer-directives-npm-0.47.6-17c276e275-70970ef227.zip"; sha512 = "70970ef227fa65a5f919cbea4243adada200b6470be4048c9625b562b9c91441084ba1da15e4d48555439006ddf1d13dc5ac70195d8f6ecd7674b02a1e1f2aa5"; };
"@unocss/transformer-variant-group@npm:0.47.6" = { filename = "@unocss-transformer-variant-group-npm-0.47.6-147e3f177a-a05683c35e.zip"; sha512 = "a05683c35e8b411935bff650a528232f67e312ad75b34441afc2f36ef5b7ecb8dfe7d5fb791719779a53b856cac3ae7157f6a43f86d1de9ae74dfb448159d393"; };
"@unocss/vite@npm:0.47.6" = { filename = "@unocss-vite-npm-0.47.6-061ca77ae3-7dc31f8fb7.zip"; sha512 = "7dc31f8fb7a12c2ffcaed0cd9cf2de29a3e1cd1c21f09f2f033fb09d8285fec1e7cf5be088d2dad63720d116ad1a21b141311d0ca266068133193a0365fc903e"; };
"abbrev@npm:1.1.1" = { filename = "abbrev-npm-1.1.1-3659247eab-a4a97ec07d.zip"; sha512 = "a4a97ec07d7ea112c517036882b2ac22f3109b7b19077dc656316d07d308438aac28e4d9746dc4d84bf6b1e75b4a7b0a5f3cb30592419f128ca9a8cee3bcfa17"; };
"acorn-jsx@npm:5.3.2" = { filename = "acorn-jsx-npm-5.3.2-d7594599ea-c3d3b2a89c.zip"; sha512 = "c3d3b2a89c9a056b205b69530a37b972b404ee46ec8e5b341666f9513d3163e2a4f214a71f4dfc7370f5a9c07472d2fd1c11c91c3f03d093e37637d95da98950"; };
"acorn@npm:8.8.1" = { filename = "acorn-npm-8.8.1-20e4aea981-4079b67283.zip"; sha512 = "4079b67283b94935157698831967642f24a075c52ce3feaaaafe095776dfbe15d86a1b33b1e53860fc0d062ed6c83f4284a5c87c85b9ad51853a01173da6097f"; };
"agent-base@npm:6.0.2" = { filename = "agent-base-npm-6.0.2-428f325a93-f52b6872cc.zip"; sha512 = "f52b6872cc96fd5f622071b71ef200e01c7c4c454ee68bc9accca90c98cfb39f2810e3e9aa330435835eedc8c23f4f8a15267f67c6e245d2b33757575bdac49d"; };
"agentkeepalive@npm:4.2.1" = { filename = "agentkeepalive-npm-4.2.1-b86a9fb343-39cb49ed8c.zip"; sha512 = "39cb49ed8cf217fd6da058a92828a0a84e0b74c35550f82ee0a10e1ee403c4b78ade7948be2279b188b7a7303f5d396ea2738b134731e464bf28de00a4f72a18"; };
"aggregate-error@npm:3.1.0" = { filename = "aggregate-error-npm-3.1.0-415a406f4e-1101a33f21.zip"; sha512 = "1101a33f21baa27a2fa8e04b698271e64616b886795fd43c31068c07533c7b3facfcaf4e9e0cab3624bd88f729a592f1c901a1a229c9e490eafce411a8644b79"; };
"ajv@npm:6.12.6" = { filename = "ajv-npm-6.12.6-4b5105e2b2-874972efe5.zip"; sha512 = "874972efe5c4202ab0a68379481fbd3d1b5d0a7bd6d3cc21d40d3536ebff3352a2a1fabb632d4fd2cc7fe4cbdcd5ed6782084c9bbf7f32a1536d18f9da5007d4"; };
"ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
"ansi-styles@npm:4.3.0" = { filename = "ansi-styles-npm-4.3.0-245c7d42c7-513b44c3b2.zip"; sha512 = "513b44c3b2105dd14cc42a19271e80f386466c4be574bccf60b627432f9198571ebf4ab1e4c3ba17347658f4ee1711c163d574248c0c1cdc2d5917a0ad582ec4"; };
"anymatch@npm:3.1.3" = { filename = "anymatch-npm-3.1.3-bc81d103b1-3e044fd6d1.zip"; sha512 = "3e044fd6d1d26545f235a9fe4d7a534e2029d8e59fa7fd9f2a6eb21230f6b5380ea1eaf55136e60cbf8e613544b3b766e7a6fa2102e2a3a117505466e3025dc2"; };
"aproba@npm:2.0.0" = { filename = "aproba-npm-2.0.0-8716bcfde6-5615cadcfb.zip"; sha512 = "5615cadcfb45289eea63f8afd064ab656006361020e1735112e346593856f87435e02d8dcc7ff0d11928bc7d425f27bc7c2a84f6c0b35ab0ff659c814c138a24"; };
"are-we-there-yet@npm:3.0.1" = { filename = "are-we-there-yet-npm-3.0.1-3395b1512f-52590c2486.zip"; sha512 = "52590c24860fa7173bedeb69a4c05fb573473e860197f618b9a28432ee4379049336727ae3a1f9c4cb083114601c1140cee578376164d0e651217a9843f9fe83"; };
"argparse@npm:2.0.1" = { filename = "argparse-npm-2.0.1-faff7999e6-83644b5649.zip"; sha512 = "83644b56493e89a254bae05702abf3a1101b4fa4d0ca31df1c9985275a5a5bd47b3c27b7fa0b71098d41114d8ca000e6ed90cad764b306f8a503665e4d517ced"; };
"array-union@npm:2.1.0" = { filename = "array-union-npm-2.1.0-4e4852b221-5bee12395c.zip"; sha512 = "5bee12395cba82da674931df6d0fea23c4aa4660cb3b338ced9f828782a65caa232573e6bf3968f23e0c5eb301764a382cef2f128b170a9dc59de0e36c39f98d"; };
"balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
"binary-extensions@npm:2.2.0" = { filename = "binary-extensions-npm-2.2.0-180c33fec7-ccd267956c.zip"; sha512 = "ccd267956c58d2315f5d3ea6757cf09863c5fc703e50fbeb13a7dc849b812ef76e3cf9ca8f35a0c48498776a7478d7b4a0418e1e2b8cb9cb9731f2922aaad7f8"; };
"brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
"brace-expansion@npm:2.0.1" = { filename = "brace-expansion-npm-2.0.1-17aa2616f9-a61e7cd2e8.zip"; sha512 = "a61e7cd2e8a8505e9f0036b3b6108ba5e926b4b55089eeb5550cd04a471fe216c96d4fe7e4c7f995c728c554ae20ddfc4244cad10aef255e72b62930afd233d1"; };
"braces@npm:3.0.2" = { filename = "braces-npm-3.0.2-782240b28a-e2a8e769a8.zip"; sha512 = "e2a8e769a863f3d4ee887b5fe21f63193a891c68b612ddb4b68d82d1b5f3ff9073af066c343e9867a393fe4c2555dcb33e89b937195feb9c1613d259edfcd459"; };
"buffer-crc32@npm:0.2.13" = { filename = "buffer-crc32-npm-0.2.13-c4b6fceac1-06252347ae.zip"; sha512 = "06252347ae6daca3453b94e4b2f1d3754a3b146a111d81c68924c22d91889a40623264e95e67955b1cb4a68cbedf317abeabb5140a9766ed248973096db5ce1c"; };
"busboy@npm:1.6.0" = { filename = "busboy-npm-1.6.0-ebb5cbb04b-32801e2c01.zip"; sha512 = "32801e2c0164e12106bf236291a00795c3c4e4b709ae02132883fe8478ba2ae23743b11c5735a0aae8afe65ac4b6ca4568b91f0d9fed1fdbc32ede824a73746e"; };
"cac@npm:6.7.14" = { filename = "cac-npm-6.7.14-c46284e425-45a2496a94.zip"; sha512 = "45a2496a9443abbe7f52a49b22fbe51b1905eff46e03fd5e6c98e3f85077be3f8949685a1849b1a9cd2bc3e5567dfebcf64f01ce01847baf918f1b37c839791a"; };
"cacache@npm:16.1.3" = { filename = "cacache-npm-16.1.3-4e2088ed0d-d91409e6e5.zip"; sha512 = "d91409e6e57d7d9a3a25e5dcc589c84e75b178ae8ea7de05cbf6b783f77a5fae938f6e8fda6f5257ed70000be27a681e1e44829251bfffe4c10216002f8f14e6"; };
"callsites@npm:3.1.0" = { filename = "callsites-npm-3.1.0-268f989910-072d17b6ab.zip"; sha512 = "072d17b6abb459c2ba96598918b55868af677154bec7e73d222ef95a8fdb9bbf7dae96a8421085cdad8cd190d86653b5b6dc55a4484f2e5b2e27d5e0c3fc15b3"; };
"chalk@npm:4.1.2" = { filename = "chalk-npm-4.1.2-ba8b67ab80-fe75c9d5c7.zip"; sha512 = "fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc"; };
"chokidar@npm:3.5.3" = { filename = "chokidar-npm-3.5.3-c5f9b0a56a-b49fcde401.zip"; sha512 = "b49fcde40176ba007ff361b198a2d35df60d9bb2a5aab228279eb810feae9294a6b4649ab15981304447afe1e6ffbf4788ad5db77235dc770ab777c6e771980c"; };
"chownr@npm:2.0.0" = { filename = "chownr-npm-2.0.0-638f1c9c61-c57cf9dd07.zip"; sha512 = "c57cf9dd0791e2f18a5ee9c1a299ae6e801ff58fee96dc8bfd0dcb4738a6ce58dd252a3605b1c93c6418fe4f9d5093b28ffbf4d66648cb2a9c67eaef9679be2f"; };
"clean-stack@npm:2.2.0" = { filename = "clean-stack-npm-2.2.0-a8ce435a5c-2ac8cd2b2f.zip"; sha512 = "2ac8cd2b2f5ec986a3c743935ec85b07bc174d5421a5efc8017e1f146a1cf5f781ae962618f416352103b32c9cd7e203276e8c28241bbe946160cab16149fb68"; };
"color-convert@npm:2.0.1" = { filename = "color-convert-npm-2.0.1-79730e935b-79e6bdb9fd.zip"; sha512 = "79e6bdb9fd479a205c71d89574fccfb22bd9053bd98c6c4d870d65c132e5e904e6034978e55b43d69fcaa7433af2016ee203ce76eeba9cfa554b373e7f7db336"; };
"color-name@npm:1.1.4" = { filename = "color-name-npm-1.1.4-025792b0ea-b044585952.zip"; sha512 = "b0445859521eb4021cd0fb0cc1a75cecf67fceecae89b63f62b201cca8d345baf8b952c966862a9d9a2632987d4f6581f0ec8d957dfacece86f0a7919316f610"; };
"color-support@npm:1.1.3" = { filename = "color-support-npm-1.1.3-3be5c53455-9b73568176.zip"; sha512 = "9b7356817670b9a13a26ca5af1c21615463b500783b739b7634a0c2047c16cef4b2865d7576875c31c3cddf9dd621fa19285e628f20198b233a5cfdda6d0793b"; };
"colorette@npm:2.0.19" = { filename = "colorette-npm-2.0.19-f73dfe6a4e-888cf5493f.zip"; sha512 = "888cf5493f781e5fcf54ce4d49e9d7d698f96ea2b2ef67906834bb319a392c667f9ec69f4a10e268d2946d13a9503d2d19b3abaaaf174e3451bfe91fb9d82427"; };
"concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
"consola@npm:2.15.3" = { filename = "consola-npm-2.15.3-7b4cf44fed-8ef7a09b70.zip"; sha512 = "8ef7a09b703ec67ac5c389a372a33b6dc97eda6c9876443a60d76a3076eea0259e7f67a4e54fd5a52f97df73690822d090cf8b7e102b5761348afef7c6d03e28"; };
"console-control-strings@npm:1.1.0" = { filename = "console-control-strings-npm-1.1.0-e3160e5275-8755d76787.zip"; sha512 = "8755d76787f94e6cf79ce4666f0c5519906d7f5b02d4b884cf41e11dcd759ed69c57da0670afd9236d229a46e0f9cf519db0cd829c6dca820bb5a5c3def584ed"; };
"cookie@npm:0.5.0" = { filename = "cookie-npm-0.5.0-e2d58a161a-1f4bd2ca57.zip"; sha512 = "1f4bd2ca5765f8c9689a7e8954183f5332139eb72b6ff783d8947032ec1fdf43109852c178e21a953a30c0dd42257828185be01b49d1eb1a67fd054ca588a180"; };
"cross-spawn@npm:7.0.3" = { filename = "cross-spawn-npm-7.0.3-e4ff3e65b3-671cc7c728.zip"; sha512 = "671cc7c7288c3a8406f3c69a3ae2fc85555c04169e9d611def9a675635472614f1c0ed0ef80955d5b6d4e724f6ced67f0ad1bb006c2ea643488fcfef994d7f52"; };
"css-tree@npm:2.3.1" = { filename = "css-tree-npm-2.3.1-6540d78e26-493cc24b5c.zip"; sha512 = "493cc24b5c22b05ee5314b8a0d72d8a5869491c1458017ae5ed75aeb6c3596637dbe1b11dac2548974624adec9f7a1f3a6cf40593dc1f9185eb0e8279543fbc0"; };
"debug@npm:4.3.4" = { filename = "debug-npm-4.3.4-4513954577-3dbad3f94e.zip"; sha512 = "3dbad3f94ea64f34431a9cbf0bafb61853eda57bff2880036153438f50fb5a84f27683ba0d8e5426bf41a8c6ff03879488120cf5b3a761e77953169c0600a708"; };
"deep-is@npm:0.1.4" = { filename = "deep-is-npm-0.1.4-88938b5a67-edb65dd0d7.zip"; sha512 = "edb65dd0d7d1b9c40b2f50219aef30e116cedd6fc79290e740972c132c09106d2e80aa0bc8826673dd5a00222d4179c84b36a790eef63a4c4bca75a37ef90804"; };
"deepmerge@npm:4.2.2" = { filename = "deepmerge-npm-4.2.2-112165ced2-a8c43a1ed8.zip"; sha512 = "a8c43a1ed8d6d1ed2b5bf569fa4c8eb9f0924034baf75d5d406e47e157a451075c4db353efea7b6bcc56ec48116a8ce72fccf867b6e078e7c561904b5897530b"; };
"defu@npm:6.1.1" = { filename = "defu-npm-6.1.1-ffebd33f42-51d05b4829.zip"; sha512 = "51d05b48297fca6c5a0ac73558f1c6182eca544c9ac7b290692ec7e165d8c5cd20d772c58b0777a8a1186fa25f49c19d28f095982a9e478d33857d46e5fa5e48"; };
"delegates@npm:1.0.0" = { filename = "delegates-npm-1.0.0-9b1942d75f-a51744d9b5.zip"; sha512 = "a51744d9b53c164ba9c0492471a1a2ffa0b6727451bdc89e31627fdf4adda9d51277cfcbfb20f0a6f08ccb3c436f341df3e92631a3440226d93a8971724771fd"; };
"depd@npm:1.1.2" = { filename = "depd-npm-1.1.2-b0c8414da7-6b406620d2.zip"; sha512 = "6b406620d269619852885ce15965272b829df6f409724415e0002c8632ab6a8c0a08ec1f0bd2add05dc7bd7507606f7e2cc034fa24224ab829580040b835ecd9"; };
"destr@npm:1.2.2" = { filename = "destr-npm-1.2.2-7e9fbb823a-3906b49513.zip"; sha512 = "3906b49513a64d8442dacb8b798c59d66257ded4ccd2ef1d99b58644d4aa6b30ca61f9a9823d3dcbc78b4db812596e53e85e499f39a498b3b165a045b5228b2b"; };
"detect-indent@npm:6.1.0" = { filename = "detect-indent-npm-6.1.0-d8c441ff7a-ab953a73c7.zip"; sha512 = "ab953a73c72dbd4e8fc68e4ed4bfd92c97eb6c43734af3900add963fd3a9316f3bc0578b018b24198d4c31a358571eff5f0656e81a1f3b9ad5c547d58b2d093d"; };
"devalue@npm:4.2.0" = { filename = "devalue-npm-4.2.0-f0a5dc655a-29f29f7225.zip"; sha512 = "29f29f72255b6330030773e02def96aa118dc410f5f2d2d389d674068bd2a698668421a0d2176d7c98e7941cbe5d535a251002d589ecc222f6e2b16783351b3d"; };
"dir-glob@npm:3.0.1" = { filename = "dir-glob-npm-3.0.1-1aea628b1b-fa05e18324.zip"; sha512 = "fa05e18324510d7283f55862f3161c6759a3f2f8dbce491a2fc14c8324c498286c54282c1f0e933cb930da8419b30679389499b919122952a4f8592362ef4615"; };
"doctrine@npm:3.0.0" = { filename = "doctrine-npm-3.0.0-c6f1615f04-fd7673ca77.zip"; sha512 = "fd7673ca77fe26cd5cba38d816bc72d641f500f1f9b25b83e8ce28827fe2da7ad583a8da26ab6af85f834138cf8dae9f69b0cd6ab925f52ddab1754db44d99ce"; };
"duplexer@npm:0.1.2" = { filename = "duplexer-npm-0.1.2-952c810235-62ba61a830.zip"; sha512 = "62ba61a830c56801db28ff6305c7d289b6dc9f859054e8c982abd8ee0b0a14d2e9a8e7d086ffee12e868d43e2bbe8a964be55ddbd8c8957714c87373c7a4f9b0"; };
"emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
"encoding@npm:0.1.13" = { filename = "encoding-npm-0.1.13-82a1837d30-bb98632f8f.zip"; sha512 = "bb98632f8ffa823996e508ce6a58ffcf5856330fde839ae42c9e1f436cc3b5cc651d4aeae72222916545428e54fd0f6aa8862fd8d25bdbcc4589f1e3f3715e7f"; };
"env-paths@npm:2.2.1" = { filename = "env-paths-npm-2.2.1-7c7577428c-65b5df55a8.zip"; sha512 = "65b5df55a8bab92229ab2b40dad3b387fad24613263d103a97f91c9fe43ceb21965cd3392b1ccb5d77088021e525c4e0481adb309625d0cb94ade1d1fb8dc17e"; };
"err-code@npm:2.0.3" = { filename = "err-code-npm-2.0.3-082e0ff9a7-8b7b1be20d.zip"; sha512 = "8b7b1be20d2de12d2255c0bc2ca638b7af5171142693299416e6a9339bd7d88fc8d7707d913d78e0993176005405a236b066b45666b27b797252c771156ace54"; };
"es6-promise@npm:3.3.1" = { filename = "es6-promise-npm-3.3.1-876231af5b-ce4044009c.zip"; sha512 = "ce4044009c2b78db18b15212338eb711cd8a4d485961bc9ec18bb24e8c1e91c96d3295b0fcf63066fc0fa1b0ade36da05e6657827d4336dece382be2429b8398"; };
"esbuild@npm:0.16.7" = { filename = "esbuild-npm-0.16.7-677c656610-5373294210.zip"; sha512 = "53732942109a8a22d647810d90623dd48418f49fd9d1613688585a6f81677fd8525f53658778a7b92f1124cdfbf73e6efb74385be52cf6aa11aa97f8397ec93c"; };
"escape-string-regexp@npm:4.0.0" = { filename = "escape-string-regexp-npm-4.0.0-4b531d8d59-98b48897d9.zip"; sha512 = "98b48897d93060f2322108bf29db0feba7dd774be96cd069458d1453347b25ce8682ecc39859d4bca2203cc0ab19c237bcc71755eff49a0f8d90beadeeba5cc5"; };
"eslint-config-prettier@npm:8.5.0" = { filename = "eslint-config-prettier-npm-8.5.0-a1dd58b6d8-0d0f5c32e7.zip"; sha512 = "0d0f5c32e7a0ad91249467ce71ca92394ccd343178277d318baf32063b79ea90216f4c81d1065d60f96366fdc60f151d4d68ae7811a58bd37228b84c2083f893"; };
"eslint-plugin-svelte3@npm:4.0.0" = { filename = "eslint-plugin-svelte3-npm-4.0.0-9fd6611586-5e9ddddede.zip"; sha512 = "5e9ddddedee44ac099290cda6e86f412c6f4f2cbdeee860eb2b617c66d3cca7699638c6191ed55c4a7651b57b8387202f62b5b0e0417219c59cdd084dcab4e07"; };
"eslint-scope@npm:5.1.1" = { filename = "eslint-scope-npm-5.1.1-71fe59b18a-47e4b6a3f0.zip"; sha512 = "47e4b6a3f0cc29c7feedee6c67b225a2da7e155802c6ea13bbef4ac6b9e10c66cd2dcb987867ef176292bf4e64eccc680a49e35e9e9c669f4a02bac17e86abdb"; };
"eslint-scope@npm:7.1.1" = { filename = "eslint-scope-npm-7.1.1-23935eb377-9f6e974ab2.zip"; sha512 = "9f6e974ab2db641ca8ab13508c405b7b859e72afe9f254e8131ff154d2f40c99ad4545ce326fd9fde3212ff29707102562a4834f1c48617b35d98c71a97fbf3e"; };
"eslint-utils@npm:3.0.0" = { filename = "eslint-utils-npm-3.0.0-630b3a4013-0668fe02f5.zip"; sha512 = "0668fe02f5adab2e5a367eee5089f4c39033af20499df88fe4e6aba2015c20720404d8c3d6349b6f716b08fdf91b9da4e5d5481f265049278099c4c836ccb619"; };
"eslint-visitor-keys@npm:2.1.0" = { filename = "eslint-visitor-keys-npm-2.1.0-c31806b6b9-e3081d7dd2.zip"; sha512 = "e3081d7dd2611a35f0388bbdc2f5da60b3a3c5b8b6e928daffff7391146b434d691577aa95064c8b7faad0b8a680266bcda0a42439c18c717b80e6718d7e267d"; };
"eslint-visitor-keys@npm:3.3.0" = { filename = "eslint-visitor-keys-npm-3.3.0-d329af7c8c-d59e68a7c5.zip"; sha512 = "d59e68a7c5a6d0146526b0eec16ce87fbf97fe46b8281e0d41384224375c4e52f5ffb9e16d48f4ea50785cde93f766b0c898e31ab89978d88b0e1720fbfb7808"; };
"eslint@npm:8.29.0" = { filename = "eslint-npm-8.29.0-289be12b40-e05204b059.zip"; sha512 = "e05204b05907b82d910983995cb946e0ba62ca514eb2b6791c43f623333b143564a2eee0139909d31c10935c21877d815b1f76dd674a59cb91c471064325c4ab"; };
"esm-env@npm:1.0.0" = { filename = "esm-env-npm-1.0.0-ed023ad58a-3372b918eb.zip"; sha512 = "3372b918ebb213b2c31e9a6ebc437e1f20062363413f837b6ca4c47bda38d7ba983c3a1a8eb8d9d8434969e9366bba8632743f1b8c7cf637a9c8a25ae95d865e"; };
"espree@npm:9.4.1" = { filename = "espree-npm-9.4.1-b88faf10bc-4d266b0cf8.zip"; sha512 = "4d266b0cf81c7dfe69e542c7df0f246e78d29f5b04dda36e514eb4c7af117ee6cfbd3280e560571ed82ff6c9c3f0003c05b82583fc7a94006db7497c4fe4270e"; };
"esquery@npm:1.4.0" = { filename = "esquery-npm-1.4.0-f39408b1a7-a0807e17ab.zip"; sha512 = "a0807e17abd7fbe5fbd4fab673038d6d8a50675cdae6b04fbaa520c34581be0c5fa24582990e8acd8854f671dd291c78bb2efb9e0ed5b62f33bac4f9cf820210"; };
"esrecurse@npm:4.3.0" = { filename = "esrecurse-npm-4.3.0-10b86a887a-ebc17b1a33.zip"; sha512 = "ebc17b1a33c51cef46fdc28b958994b1dc43cd2e86237515cbc3b4e5d2be6a811b2315d0a1a4d9d340b6d2308b15322f5c8291059521cc5f4802f65e7ec32837"; };
"estraverse@npm:4.3.0" = { filename = "estraverse-npm-4.3.0-920a32f3c6-a6299491f9.zip"; sha512 = "a6299491f9940bb246124a8d44b7b7a413a8336f5436f9837aaa9330209bd9ee8af7e91a654a3545aee9c54b3308e78ee360cef1d777d37cfef77d2fa33b5827"; };
"estraverse@npm:5.3.0" = { filename = "estraverse-npm-5.3.0-03284f8f63-072780882d.zip"; sha512 = "072780882dc8416ad144f8fe199628d2b3e7bbc9989d9ed43795d2c90309a2047e6bc5979d7e2322a341163d22cfad9e21f4110597fe487519697389497e4e2b"; };
"estree-walker@npm:2.0.2" = { filename = "estree-walker-npm-2.0.2-dfab42f65c-6151e6f982.zip"; sha512 = "6151e6f9828abe2259e57f5fd3761335bb0d2ebd76dc1a01048ccee22fabcfef3c0859300f6d83ff0d1927849368775ec5a6d265dde2f6de5a1be1721cd94efc"; };
"esutils@npm:2.0.3" = { filename = "esutils-npm-2.0.3-f865beafd5-22b5b08f74.zip"; sha512 = "22b5b08f74737379a840b8ed2036a5fb35826c709ab000683b092d9054e5c2a82c27818f12604bfc2a9a76b90b6834ef081edbc1c7ae30d1627012e067c6ec87"; };
"execa@npm:5.1.1" = { filename = "execa-npm-5.1.1-191347acf5-fba9022c8c.zip"; sha512 = "fba9022c8c8c15ed862847e94c252b3d946036d7547af310e344a527e59021fd8b6bb0723883ea87044dc4f0201f949046993124a42ccb0855cae5bf8c786343"; };
"fast-deep-equal@npm:3.1.3" = { filename = "fast-deep-equal-npm-3.1.3-790edcfcf5-e21a9d8d84.zip"; sha512 = "e21a9d8d84f53493b6aa15efc9cfd53dd5b714a1f23f67fb5dc8f574af80df889b3bce25dc081887c6d25457cce704e636395333abad896ccdec03abaf1f3f9d"; };
"fast-glob@npm:3.2.12" = { filename = "fast-glob-npm-3.2.12-162763bbae-0b1990f6ce.zip"; sha512 = "0b1990f6ce831c7e28c4d505edcdaad8e27e88ab9fa65eedadb730438cfc7cde4910d6c975d6b7b8dc8a73da4773702ebcfcd6e3518e73938bb1383badfe01c2"; };
"fast-json-stable-stringify@npm:2.1.0" = { filename = "fast-json-stable-stringify-npm-2.1.0-02e8905fda-b191531e36.zip"; sha512 = "b191531e36c607977e5b1c47811158733c34ccb3bfde92c44798929e9b4154884378536d26ad90dfecd32e1ffc09c545d23535ad91b3161a27ddbb8ebe0cbecb"; };
"fast-levenshtein@npm:2.0.6" = { filename = "fast-levenshtein-npm-2.0.6-fcd74b8df5-92cfec0a8d.zip"; sha512 = "92cfec0a8dfafd9c7a15fba8f2cc29cd0b62b85f056d99ce448bbcd9f708e18ab2764bda4dd5158364f4145a7c72788538994f0d1787b956ef0d1062b0f7c24c"; };
"fastq@npm:1.14.0" = { filename = "fastq-npm-1.14.0-7344c77718-da2c05ec14.zip"; sha512 = "da2c05ec1446ef77b8ba2b76619c90d483404f5087e71e77469fbee797280a1f4ef26a63be15b2377198bc20d09fdf25c7d6e1e492a1e568a29dfdd9bcb7538c"; };
"file-entry-cache@npm:6.0.1" = { filename = "file-entry-cache-npm-6.0.1-31965cf0af-f49701feaa.zip"; sha512 = "f49701feaa6314c8127c3c2f6173cfefff17612f5ed2daaafc6da13b5c91fd43e3b2a58fd0d63f9f94478a501b167615931e7200e31485e320f74a33885a9c74"; };
"fill-range@npm:7.0.1" = { filename = "fill-range-npm-7.0.1-b8b1817caa-cc283f4e65.zip"; sha512 = "cc283f4e65b504259e64fd969bcf4def4eb08d85565e906b7d36516e87819db52029a76b6363d0f02d0d532f0033c9603b9e2d943d56ee3b0d4f7ad3328ff917"; };
"find-up@npm:5.0.0" = { filename = "find-up-npm-5.0.0-e03e9b796d-07955e3573.zip"; sha512 = "07955e357348f34660bde7920783204ff5a26ac2cafcaa28bace494027158a97b9f56faaf2d89a6106211a8174db650dd9f503f9c0d526b1202d5554a00b9095"; };
"flat-cache@npm:3.0.4" = { filename = "flat-cache-npm-3.0.4-ee77e5911e-4fdd10ecbc.zip"; sha512 = "4fdd10ecbcbf7d520f9040dd1340eb5dfe951e6f0ecf2252edeec03ee68d989ec8b9a20f4434270e71bcfd57800dc09b3344fca3966b2eb8f613072c7d9a2365"; };
"flatted@npm:3.2.7" = { filename = "flatted-npm-3.2.7-0da10b7c56-427633049d.zip"; sha512 = "427633049d55bdb80201c68f7eb1cbd533e03eac541f97d3aecab8c5526f12a20ccecaeede08b57503e772c769e7f8680b37e8d482d1e5f8d7e2194687f9ea35"; };
"fs-minipass@npm:2.1.0" = { filename = "fs-minipass-npm-2.1.0-501ef87306-1b8d128dae.zip"; sha512 = "1b8d128dae2ac6cc94230cc5ead341ba3e0efaef82dab46a33d171c044caaa6ca001364178d42069b2809c35a1c3c35079a32107c770e9ffab3901b59af8c8b1"; };
"fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
"fsevents@npm:2.3.2" = { filename = "fsevents-npm-2.3.2-a881d6ac9f-97ade64e75.zip"; sha512 = "97ade64e75091afee5265e6956cb72ba34db7819b4c3e94c431d4be2b19b8bb7a2d4116da417950c3425f17c8fe693d25e20212cac583ac1521ad066b77ae31f"; };
"function-bind@npm:1.1.1" = { filename = "function-bind-npm-1.1.1-b56b322ae9-b32fbaebb3.zip"; sha512 = "b32fbaebb3f8ec4969f033073b43f5c8befbb58f1a79e12f1d7490358150359ebd92f49e72ff0144f65f2c48ea2a605bff2d07965f548f6474fd8efd95bf361a"; };
"gauge@npm:4.0.4" = { filename = "gauge-npm-4.0.4-8f878385e9-788b6bfe52.zip"; sha512 = "788b6bfe52f1dd8e263cda800c26ac0ca2ff6de0b6eee2fe0d9e3abf15e149b651bd27bf5226be10e6e3edb5c4e5d5985a5a1a98137e7a892f75eff76467ad2d"; };
"get-stream@npm:6.0.1" = { filename = "get-stream-npm-6.0.1-83e51a4642-e04ecece32.zip"; sha512 = "e04ecece32c92eebf5b8c940f51468cd53554dcbb0ea725b2748be583c9523d00128137966afce410b9b051eb2ef16d657cd2b120ca8edafcf5a65e81af63cad"; };
"glob-parent@npm:5.1.2" = { filename = "glob-parent-npm-5.1.2-021ab32634-f4f2bfe242.zip"; sha512 = "f4f2bfe2425296e8a47e36864e4f42be38a996db40420fe434565e4480e3322f18eb37589617a98640c5dc8fdec1a387007ee18dbb1f3f5553409c34d17f425e"; };
"glob-parent@npm:6.0.2" = { filename = "glob-parent-npm-6.0.2-2cbef12738-c13ee97978.zip"; sha512 = "c13ee97978bef4f55106b71e66428eb1512e71a7466ba49025fc2aec59a5bfb0954d5abd58fc5ee6c9b076eef4e1f6d3375c2e964b88466ca390da4419a786a8"; };
"glob@npm:7.2.3" = { filename = "glob-npm-7.2.3-2d866d17a5-29452e97b3.zip"; sha512 = "29452e97b38fa704dabb1d1045350fb2467cf0277e155aa9ff7077e90ad81d1ea9d53d3ee63bd37c05b09a065e90f16aec4a65f5b8de401d1dac40bc5605d133"; };
"glob@npm:8.0.3" = { filename = "glob-npm-8.0.3-750f909025-50bcdea19d.zip"; sha512 = "50bcdea19d8e79d8de5f460b1939ffc2b3299eac28deb502093fdca22a78efebc03e66bf54f0abc3d3d07d8134d19a32850288b7440d77e072aa55f9d33b18c5"; };
"globals@npm:13.19.0" = { filename = "globals-npm-13.19.0-a63c75a2dd-a000dbd00b.zip"; sha512 = "a000dbd00bcf28f0941d8a29c3522b1c3b8e4bfe4e60e262c477a550c3cbbe8dbe2925a6905f037acd40f9a93c039242e1f7079c76b0fd184bc41dcc3b5c8e2e"; };
"globalyzer@npm:0.1.0" = { filename = "globalyzer-npm-0.1.0-3982d25961-419a0f95ba.zip"; sha512 = "419a0f95ba542534fac0842964d31b3dc2936a479b2b1a8a62bad7e8b61054faa9b0a06ad9f2e12593396b9b2621cac93358d9b3071d33723fb1778608d358a1"; };
"globby@npm:11.1.0" = { filename = "globby-npm-11.1.0-bdcdf20c71-b4be8885e0.zip"; sha512 = "b4be8885e0cfa018fc783792942d53926c35c50b3aefd3fdcfb9d22c627639dc26bd2327a40a0b74b074100ce95bb7187bfeae2f236856aa3de183af7a02aea6"; };
"globrex@npm:0.1.2" = { filename = "globrex-npm-0.1.2-ddda94f2d0-adca162494.zip"; sha512 = "adca162494a176ce9ecf4dd232f7b802956bb1966b37f60c15e49d2e7d961b66c60826366dc2649093cad5a0d69970cfa8875bd1695b5a1a2f33dcd2aa88da3c"; };
"graceful-fs@npm:4.2.10" = { filename = "graceful-fs-npm-4.2.10-79c70989ca-3f109d70ae.zip"; sha512 = "3f109d70ae123951905d85032ebeae3c2a5a7a997430df00ea30df0e3a6c60cf6689b109654d6fdacd28810a053348c4d14642da1d075049e6be1ba5216218da"; };
"grapheme-splitter@npm:1.0.4" = { filename = "grapheme-splitter-npm-1.0.4-648f2bf509-0c22ec54de.zip"; sha512 = "0c22ec54dee1b05cd480f78cf14f732cb5b108edc073572c4ec205df4cd63f30f8db8025afc5debc8835a8ddeacf648a1c7992fe3dcd6ad38f9a476d84906620"; };
"gzip-size@npm:6.0.0" = { filename = "gzip-size-npm-6.0.0-d5b52fdbf1-2df97f3596.zip"; sha512 = "2df97f359696ad154fc171dcb55bc883fe6e833bca7a65e457b9358f3cb6312405ed70a8da24a77c1baac0639906cd52358dc0ce2ec1a937eaa631b934c94194"; };
"has-flag@npm:4.0.0" = { filename = "has-flag-npm-4.0.0-32af9f0536-261a135703.zip"; sha512 = "261a1357037ead75e338156b1f9452c016a37dcd3283a972a30d9e4a87441ba372c8b81f818cd0fbcd9c0354b4ae7e18b9e1afa1971164aef6d18c2b6095a8ad"; };
"has-unicode@npm:2.0.1" = { filename = "has-unicode-npm-2.0.1-893adb4747-1eab07a743.zip"; sha512 = "1eab07a7436512db0be40a710b29b5dc21fa04880b7f63c9980b706683127e3c1b57cb80ea96d47991bdae2dfe479604f6a1ba410106ee1046a41d1bd0814400"; };
"has@npm:1.0.3" = { filename = "has-npm-1.0.3-b7f00631c1-b9ad53d53b.zip"; sha512 = "b9ad53d53be4af90ce5d1c38331e712522417d017d5ef1ebd0507e07c2fbad8686fffb8e12ddecd4c39ca9b9b47431afbb975b8abf7f3c3b82c98e9aad052792"; };
"http-cache-semantics@npm:4.1.0" = { filename = "http-cache-semantics-npm-4.1.0-860520a31f-974de94a81.zip"; sha512 = "974de94a81c5474be07f269f9fd8383e92ebb5a448208223bfb39e172a9dbc26feff250192ecc23b9593b3f92098e010406b0f24bd4d588d631f80214648ed42"; };
"http-proxy-agent@npm:5.0.0" = { filename = "http-proxy-agent-npm-5.0.0-7f1f121b83-e2ee1ff165.zip"; sha512 = "e2ee1ff1656a131953839b2a19cd1f3a52d97c25ba87bd2559af6ae87114abf60971e498021f9b73f9fd78aea8876d1fb0d4656aac8a03c6caa9fc175f22b786"; };
"https-proxy-agent@npm:5.0.1" = { filename = "https-proxy-agent-npm-5.0.1-42d65f358e-571fccdf38.zip"; sha512 = "571fccdf38184f05943e12d37d6ce38197becdd69e58d03f43637f7fa1269cf303a7d228aa27e5b27bbd3af8f09fd938e1c91dcfefff2df7ba77c20ed8dfc765"; };
"human-signals@npm:2.1.0" = { filename = "human-signals-npm-2.1.0-f75815481d-b87fd89fce.zip"; sha512 = "b87fd89fce72391625271454e70f67fe405277415b48bcc0117ca73d31fa23a4241787afdc8d67f5a116cf37258c052f59ea82daffa72364d61351423848e3b8"; };
"humanize-ms@npm:1.2.1" = { filename = "humanize-ms-npm-1.2.1-e942bd7329-9c7a74a282.zip"; sha512 = "9c7a74a2827f9294c009266c82031030eae811ca87b0da3dceb8d6071b9bde22c9f3daef0469c3c533cc67a97d8a167cd9fc0389350e5f415f61a79b171ded16"; };
"iconv-lite@npm:0.6.3" = { filename = "iconv-lite-npm-0.6.3-24b8aae27e-3f60d47a5c.zip"; sha512 = "3f60d47a5c8fc3313317edfd29a00a692cc87a19cac0159e2ce711d0ebc9019064108323b5e493625e25594f11c6236647d8e256fbe7a58f4a3b33b89e6d30bf"; };
"ignore@npm:5.2.1" = { filename = "ignore-npm-5.2.1-208dc99ae8-7251d00cba.zip"; sha512 = "7251d00cba49fe88c4f3565fadeb4aa726ba38294a9a79ffed542edc47bafd989d4b2ccf65700c5b1b26a1e91dfc7218fb23017937c79216025d5caeec0ee9d5"; };
"import-fresh@npm:3.3.0" = { filename = "import-fresh-npm-3.3.0-3e34265ca9-2cacfad06e.zip"; sha512 = "2cacfad06e652b1edc50be650f7ec3be08c5e5a6f6d12d035c440a42a8cc028e60a5b99ca08a77ab4d6b1346da7d971915828f33cdab730d3d42f08242d09baa"; };
"imurmurhash@npm:0.1.4" = { filename = "imurmurhash-npm-0.1.4-610c5068a0-7cae75c8cd.zip"; sha512 = "7cae75c8cd9a50f57dadd77482359f659eaebac0319dd9368bcd1714f55e65badd6929ca58569da2b6494ef13fdd5598cd700b1eba23f8b79c5f19d195a3ecf7"; };
"indent-string@npm:4.0.0" = { filename = "indent-string-npm-4.0.0-7b717435b2-824cfb9929.zip"; sha512 = "824cfb9929d031dabf059bebfe08cf3137365e112019086ed3dcff6a0a7b698cb80cf67ccccde0e25b9e2d7527aa6cc1fed1ac490c752162496caba3e6699612"; };
"infer-owner@npm:1.0.4" = { filename = "infer-owner-npm-1.0.4-685ac3d2af-181e732764.zip"; sha512 = "181e732764e4a0611576466b4b87dac338972b839920b2a8cde43642e4ed6bd54dc1fb0b40874728f2a2df9a1b097b8ff83b56d5f8f8e3927f837fdcb47d8a89"; };
"inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
"inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
"ip@npm:2.0.0" = { filename = "ip-npm-2.0.0-204facb3cc-cfcfac6b87.zip"; sha512 = "cfcfac6b873b701996d71ec82a7dd27ba92450afdb421e356f44044ed688df04567344c36cbacea7d01b1c39a4c732dc012570ebe9bebfb06f27314bca625349"; };
"is-binary-path@npm:2.1.0" = { filename = "is-binary-path-npm-2.1.0-e61d46f557-84192eb88c.zip"; sha512 = "84192eb88cff70d320426f35ecd63c3d6d495da9d805b19bc65b518984b7c0760280e57dbf119b7e9be6b161784a5a673ab2c6abe83abb5198a432232ad5b35c"; };
"is-core-module@npm:2.11.0" = { filename = "is-core-module-npm-2.11.0-70061e141a-f96fd490c6.zip"; sha512 = "f96fd490c6b48eb4f6d10ba815c6ef13f410b0ba6f7eb8577af51697de523e5f2cd9de1c441b51d27251bf0e4aebc936545e33a5d26d5d51f28d25698d4a8bab"; };
"is-extglob@npm:2.1.1" = { filename = "is-extglob-npm-2.1.1-0870ea68b5-df033653d0.zip"; sha512 = "df033653d06d0eb567461e58a7a8c9f940bd8c22274b94bf7671ab36df5719791aae15eef6d83bbb5e23283967f2f984b8914559d4449efda578c775c4be6f85"; };
"is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
"is-glob@npm:4.0.3" = { filename = "is-glob-npm-4.0.3-cb87bf1bdb-d381c1319f.zip"; sha512 = "d381c1319fcb69d341cc6e6c7cd588e17cd94722d9a32dbd60660b993c4fb7d0f19438674e68dfec686d09b7c73139c9166b47597f846af387450224a8101ab4"; };
"is-lambda@npm:1.0.1" = { filename = "is-lambda-npm-1.0.1-7ab55bc8a8-93a32f0194.zip"; sha512 = "93a32f01940220532e5948538699ad610d5924ac86093fcee83022252b363eb0cc99ba53ab084a04e4fb62bf7b5731f55496257a4c38adf87af9c4d352c71c35"; };
"is-number@npm:7.0.0" = { filename = "is-number-npm-7.0.0-060086935c-456ac6f8e0.zip"; sha512 = "456ac6f8e0f3111ed34668a624e45315201dff921e5ac181f8ec24923b99e9f32ca1a194912dc79d539c97d33dba17dc635202ff0b2cf98326f608323276d27a"; };
"is-path-inside@npm:3.0.3" = { filename = "is-path-inside-npm-3.0.3-2ea0ef44fd-abd50f0618.zip"; sha512 = "abd50f06186a052b349c15e55b182326f1936c89a78bf6c8f2b707412517c097ce04bc49a0ca221787bc44e1049f51f09a2ffb63d22899051988d3a618ba13e9"; };
"is-stream@npm:2.0.1" = { filename = "is-stream-npm-2.0.1-c802db55e7-b8e05ccdf9.zip"; sha512 = "b8e05ccdf96ac330ea83c12450304d4a591f9958c11fd17bed240af8d5ffe08aedafa4c0f4cfccd4d28dc9d4d129daca1023633d5c11601a6cbc77521f6fae66"; };
"isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
"jiti@npm:1.16.0" = { filename = "jiti-npm-1.16.0-a3cbfd13e3-28844cd691.zip"; sha512 = "28844cd69168fd0491b296d4925e0034cc9f23aba51bdb94b896818e444059092af838f98d406477dc1b6e0ca15a5ff4522e060bf3f289f9e1ca1ee572a54e6b"; };
"js-sdsl@npm:4.2.0" = { filename = "js-sdsl-npm-4.2.0-f34411d30f-2cd0885f72.zip"; sha512 = "2cd0885f7212afb355929d72ca105cb37de7e95ad6031e6a32619eaefa46735a7d0fb682641a0ba666e1519cb138fe76abc1eea8a34e224140c9d94c995171f1"; };
"js-yaml@npm:4.1.0" = { filename = "js-yaml-npm-4.1.0-3606f32312-c7830dfd45.zip"; sha512 = "c7830dfd456c3ef2c6e355cc5a92e6700ceafa1d14bba54497b34a99f0376cecbb3e9ac14d3e5849b426d5a5140709a66237a8c991c675431271c4ce5504151a"; };
"json-schema-traverse@npm:0.4.1" = { filename = "json-schema-traverse-npm-0.4.1-4759091693-7486074d3b.zip"; sha512 = "7486074d3ba247769fda17d5181b345c9fb7d12e0da98b22d1d71a5db9698d8b4bd900a3ec1a4ffdd60846fc2556274a5c894d0c48795f14cb03aeae7b55260b"; };
"json-stable-stringify-without-jsonify@npm:1.0.1" = { filename = "json-stable-stringify-without-jsonify-npm-1.0.1-b65772b28b-cff44156dd.zip"; sha512 = "cff44156ddce9c67c44386ad5cddf91925fe06b1d217f2da9c4910d01f358c6e3989c4d5a02683c7a5667f9727ff05831f7aa8ae66c8ff691c556f0884d49215"; };
"kleur@npm:4.1.5" = { filename = "kleur-npm-4.1.5-46b6135f41-1dc476e327.zip"; sha512 = "1dc476e32741acf0b1b5b0627ffd0d722e342c1b0da14de3e8ae97821327ca08f9fb944542fb3c126d90ac5f27f9d804edbe7c585bf7d12ef495d115e0f22c12"; };
"kolorist@npm:1.6.0" = { filename = "kolorist-npm-1.6.0-d7d152ff92-4d898b782c.zip"; sha512 = "4d898b782ceaaac3a51d9820a13563fcd0ed516d5493374a0e04ceda93ed4d74f9e267e8da5fb4453e508099b9f6b22e38ac1bff92fdc227081f460c003401c0"; };
"levn@npm:0.4.1" = { filename = "levn-npm-0.4.1-d183b2d7bb-12c5021c85.zip"; sha512 = "12c5021c859bd0f5248561bf139121f0358285ec545ebf48bb3d346820d5c61a4309535c7f387ed7d84361cf821e124ce346c6b7cef8ee09a67c1473b46d0fc4"; };
"local-pkg@npm:0.4.2" = { filename = "local-pkg-npm-0.4.2-534016519b-22be451353.zip"; sha512 = "22be451353c25c4411b552bf01880ebc9e995b93574b2facc7757968d888356df59199cacada14162ab53bbc9da055bb692c907b4171f008dbce45a2afc777c1"; };
"locate-path@npm:6.0.0" = { filename = "locate-path-npm-6.0.0-06a1e4c528-72eb661788.zip"; sha512 = "72eb661788a0368c099a184c59d2fee760b3831c9c1c33955e8a19ae4a21b4116e53fa736dc086cdeb9fce9f7cc508f2f92d2d3aae516f133e16a2bb59a39f5a"; };
"lodash.merge@npm:4.6.2" = { filename = "lodash.merge-npm-4.6.2-77cb4416bf-ad580b4bdb.zip"; sha512 = "ad580b4bdbb7ca1f7abf7e1bce63a9a0b98e370cf40194b03380a46b4ed799c9573029599caebc1b14e3f24b111aef72b96674a56cfa105e0f5ac70546cdc005"; };
"lru-cache@npm:6.0.0" = { filename = "lru-cache-npm-6.0.0-b4c8668fe1-f97f499f89.zip"; sha512 = "f97f499f898f23e4585742138a22f22526254fdba6d75d41a1c2526b3b6cc5747ef59c5612ba7375f42aca4f8461950e925ba08c991ead0651b4918b7c978297"; };
"lru-cache@npm:7.14.1" = { filename = "lru-cache-npm-7.14.1-d3ba9407b6-d72c6713c6.zip"; sha512 = "d72c6713c6a6d86836a7a6523b3f1ac6764768cca47ec99341c3e76db06aacd4764620e5e2cda719a36848785a52a70e531822dc2b33fb071fa709683746c104"; };
"magic-string@npm:0.25.9" = { filename = "magic-string-npm-0.25.9-0b51c0ea50-9a0e55a15c.zip"; sha512 = "9a0e55a15c7303fc360f9572a71cffba1f61451bc92c5602b1206c9d17f492403bf96f946dfce7483e66822d6b74607262e24392e87b0ac27b786e69a40e9b1a"; };
"magic-string@npm:0.26.7" = { filename = "magic-string-npm-0.26.7-07281acc06-89b0d60cbb.zip"; sha512 = "89b0d60cbb32bbf3d1e23c46ea93db082d18a8230b972027aecb10a40bba51be519ecce0674f995571e3affe917b76b09f59d8dbc9a1b2c9c4102a2b6e8a2b01"; };
"magic-string@npm:0.27.0" = { filename = "magic-string-npm-0.27.0-a60a83c0b4-273faaa50b.zip"; sha512 = "273faaa50baadb7a2df6e442eac34ad611304fc08fe16e24fe2e472fd944bfcb73ffb50d2dc972dc04e92784222002af46868cb9698b1be181c81830fd95a13e"; };
"make-fetch-happen@npm:10.2.1" = { filename = "make-fetch-happen-npm-10.2.1-f1cc7cd2df-2332eb9a8e.zip"; sha512 = "2332eb9a8ec96f1ffeeea56ccefabcb4193693597b132cd110734d50f2928842e22b84cfa1508e921b8385cdfd06dda9ad68645fed62b50fff629a580f5fb72c"; };
"mdn-data@npm:2.0.30" = { filename = "mdn-data-npm-2.0.30-bf7b39c09a-d6ac5ac743.zip"; sha512 = "d6ac5ac7439a1607df44b22738ecf83f48e66a0874e4482d6424a61c52da5cde5750f1d1229b6f5fa1b80a492be89465390da685b11f97d62b8adcc6e88189aa"; };
"merge-stream@npm:2.0.0" = { filename = "merge-stream-npm-2.0.0-2ac83efea5-6fa4dcc8d8.zip"; sha512 = "6fa4dcc8d86629705cea944a4b88ef4cb0e07656ebf223fa287443256414283dd25d91c1cd84c77987f2aec5927af1a9db6085757cb43d90eb170ebf4b47f4f4"; };
"merge2@npm:1.4.1" = { filename = "merge2-npm-1.4.1-a2507bd06c-7268db63ed.zip"; sha512 = "7268db63ed5169466540b6fb947aec313200bcf6d40c5ab722c22e242f651994619bcd85601602972d3c85bd2cc45a358a4c61937e9f11a061919a1da569b0c2"; };
"micromatch@npm:4.0.5" = { filename = "micromatch-npm-4.0.5-cfab5d7669-02a17b671c.zip"; sha512 = "02a17b671c06e8fefeeb6ef996119c1e597c942e632a21ef589154f23898c9c6a9858526246abb14f8bca6e77734aa9dcf65476fca47cedfb80d9577d52843fc"; };
"mime@npm:3.0.0" = { filename = "mime-npm-3.0.0-8d911e4c06-f43f9b7bfa.zip"; sha512 = "f43f9b7bfa64534e6b05bd6062961681aeb406a5b53673b53b683f27fcc4e739989941836a355eef831f4478923651ecc739f4a5f6e20a76487b432bfd4db928"; };
"mimic-fn@npm:2.1.0" = { filename = "mimic-fn-npm-2.1.0-4fbeb3abb4-d2421a3444.zip"; sha512 = "d2421a3444848ce7f84bd49115ddacff29c15745db73f54041edc906c14b131a38d05298dae3081667627a59b2eb1ca4b436ff2e1b80f69679522410418b478a"; };
"min-indent@npm:1.0.1" = { filename = "min-indent-npm-1.0.1-77031f50e1-bfc6dd03c5.zip"; sha512 = "bfc6dd03c5eaf623a4963ebd94d087f6f4bbbfd8c41329a7f09706b0cb66969c4ddd336abeb587bc44bc6f08e13bf90f0b374f9d71f9f01e04adc2cd6f083ef1"; };
"minimatch@npm:3.1.2" = { filename = "minimatch-npm-3.1.2-9405269906-c154e56640.zip"; sha512 = "c154e566406683e7bcb746e000b84d74465b3a832c45d59912b9b55cd50dee66e5c4b1e5566dba26154040e51672f9aa450a9aef0c97cfc7336b78b7afb9540a"; };
"minimatch@npm:5.1.1" = { filename = "minimatch-npm-5.1.1-521233e3d2-215edd0978.zip"; sha512 = "215edd0978320a3354188f84a537d45841f2449af4df4379f79b9b777e71aa4f5722cc9d1717eabd2a70d38ef76ab7b708d24d83ea6a6c909dfd8833de98b437"; };
"minimist@npm:1.2.7" = { filename = "minimist-npm-1.2.7-51d33b1371-7346574a10.zip"; sha512 = "7346574a1038ca23c32e02252f603801f09384dd1d78b69a943a4e8c2c28730b80e96193882d3d3b22a063445f460e48316b29b8a25addca2d7e5e8f75478bec"; };
"minipass-collect@npm:1.0.2" = { filename = "minipass-collect-npm-1.0.2-3b4676eab5-14df761028.zip"; sha512 = "14df761028f3e47293aee72888f2657695ec66bd7d09cae7ad558da30415fdc4752bbfee66287dcc6fd5e6a2fa3466d6c484dc1cbd986525d9393b9523d97f10"; };
"minipass-fetch@npm:2.1.2" = { filename = "minipass-fetch-npm-2.1.2-9b21a5c930-3f216be791.zip"; sha512 = "3f216be79164e915fc91210cea1850e488793c740534985da017a4cbc7a5ff50506956d0f73bb0cb60e4fe91be08b6b61ef35101706d3ef5da2c8709b5f08f91"; };
"minipass-flush@npm:1.0.5" = { filename = "minipass-flush-npm-1.0.5-efe79d9826-56269a0b22.zip"; sha512 = "56269a0b22bad756a08a94b1ffc36b7c9c5de0735a4dd1ab2b06c066d795cfd1f0ac44a0fcae13eece5589b908ecddc867f04c745c7009be0b566421ea0944cf"; };
"minipass-pipeline@npm:1.2.4" = { filename = "minipass-pipeline-npm-1.2.4-5924cb077f-b14240dac0.zip"; sha512 = "b14240dac0d29823c3d5911c286069e36d0b81173d7bdf07a7e4a91ecdef92cdff4baaf31ea3746f1c61e0957f652e641223970870e2353593f382112257971b"; };
"minipass-sized@npm:1.0.3" = { filename = "minipass-sized-npm-1.0.3-306d86f432-79076749fc.zip"; sha512 = "79076749fcacf21b5d16dd596d32c3b6bf4d6e62abb43868fac21674078505c8b15eaca4e47ed844985a4514854f917d78f588fcd029693709417d8f98b2bd60"; };
"minipass@npm:3.3.6" = { filename = "minipass-npm-3.3.6-b8d93a945b-a30d083c80.zip"; sha512 = "a30d083c8054cee83cdcdc97f97e4641a3f58ae743970457b1489ce38ee1167b3aaf7d815cd39ec7a99b9c40397fd4f686e83750e73e652b21cb516f6d845e48"; };
"minipass@npm:4.0.0" = { filename = "minipass-npm-4.0.0-2520d5ae3c-7a609afbf3.zip"; sha512 = "7a609afbf394abfcf9c48e6c90226f471676c8f2a67f07f6838871afb03215ede431d1433feffe1b855455bcb13ef0eb89162841b9796109d6fed8d89790f381"; };
"minizlib@npm:2.1.2" = { filename = "minizlib-npm-2.1.2-ea89cd0cfb-f1fdeac0b0.zip"; sha512 = "f1fdeac0b07cf8f30fcf12f4b586795b97be856edea22b5e9072707be51fc95d41487faec3f265b42973a304fe3a64acd91a44a3826a963e37b37bafde0212c3"; };
"mkdirp@npm:0.5.6" = { filename = "mkdirp-npm-0.5.6-dcd5a6b97b-0c91b721bb.zip"; sha512 = "0c91b721bb12c3f9af4b77ebf73604baf350e64d80df91754dc509491ae93bf238581e59c7188360cec7cb62fc4100959245a42cfe01834efedc5e9d068376c2"; };
"mkdirp@npm:1.0.4" = { filename = "mkdirp-npm-1.0.4-37f6ef56b9-a96865108c.zip"; sha512 = "a96865108c6c3b1b8e1d5e9f11843de1e077e57737602de1b82030815f311be11f96f09cce59bd5b903d0b29834733e5313f9301e3ed6d6f6fba2eae0df4298f"; };
"mri@npm:1.2.0" = { filename = "mri-npm-1.2.0-8ecee0357d-83f515abbc.zip"; sha512 = "83f515abbcff60150873e424894a2f65d68037e5a7fcde8a9e2b285ee9c13ac581b63cfc1e6826c4732de3aeb84902f7c1e16b7aff46cd3f897a0f757a894e85"; };
"mrmime@npm:1.0.1" = { filename = "mrmime-npm-1.0.1-d0aa4f5ddf-cc979da44b.zip"; sha512 = "cc979da44bbbffebaa8eaf7a45117e851f2d4cb46a3ada6ceb78130466a04c15a0de9a9ce1c8b8ba6f6e1b8618866b1352992bf1757d241c0ddca558b9f28a77"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"nanoid@npm:3.3.4" = { filename = "nanoid-npm-3.3.4-3d250377d6-2fddd6dee9.zip"; sha512 = "2fddd6dee994b7676f008d3ffa4ab16035a754f4bb586c61df5a22cf8c8c94017aadd360368f47d653829e0569a92b129979152ff97af23a558331e47e37cd9c"; };
"natural-compare-lite@npm:1.4.0" = { filename = "natural-compare-lite-npm-1.4.0-12b6b308ed-5222ac3986.zip"; sha512 = "5222ac3986a2b78dd6069ac62cbb52a7bf8ffc90d972ab76dfe7b01892485d229530ed20d0c62e79a6b363a663b273db3bde195a1358ce9e5f779d4453887225"; };
"natural-compare@npm:1.4.0" = { filename = "natural-compare-npm-1.4.0-97b75b362d-23ad088b08.zip"; sha512 = "23ad088b08f898fc9b53011d7bb78ec48e79de7627e01ab5518e806033861bef68d5b0cd0e2205c2f36690ac9571ff6bcb05eb777ced2eeda8d4ac5b44592c3d"; };
"negotiator@npm:0.6.3" = { filename = "negotiator-npm-0.6.3-9d50e36171-b8ffeb1e26.zip"; sha512 = "b8ffeb1e262eff7968fc90a2b6767b04cfd9842582a9d0ece0af7049537266e7b2506dfb1d107a32f06dd849ab2aea834d5830f7f4d0e5cb7d36e1ae55d021d9"; };
"node-fetch-native@npm:0.1.8" = { filename = "node-fetch-native-npm-0.1.8-42f942d60a-1cea29dc30.zip"; sha512 = "1cea29dc30e9b570b5510656f41050e7d2df70acc41937911d4374c404ac35b4592d6b6959a81f336f00f2d74b321d039b80d8a1b62eaaa395747733bc31c799"; };
"node-gyp@npm:9.3.0" = { filename = "node-gyp-npm-9.3.0-21c41a4dfd-589ddd3ed9.zip"; sha512 = "589ddd3ed967724ef425f9624bfa47cf73022640ab3eba6d556e92cdc4ddef33b63fce3a467c93b995a3f61df92eafd3c3d1e8dbe4a2c00c383334487dea99c3"; };
"nopt@npm:6.0.0" = { filename = "nopt-npm-6.0.0-5ea8050815-82149371f8.zip"; sha512 = "82149371f8be0c4b9ec2f863cc6509a7fd0fa729929c009f3a58e4eb0c9e4cae9920e8f1f8eb46e7d032fec8fb01bede7f0f41a67eb3553b7b8e14fa53de1dac"; };
"normalize-path@npm:3.0.0" = { filename = "normalize-path-npm-3.0.0-658ba7d77f-88eeb4da89.zip"; sha512 = "88eeb4da891e10b1318c4b2476b6e2ecbeb5ff97d946815ffea7794c31a89017c70d7f34b3c2ebf23ef4e9fc9fb99f7dffe36da22011b5b5c6ffa34f4873ec20"; };
"npm-run-path@npm:4.0.1" = { filename = "npm-run-path-npm-4.0.1-7aebd8bab3-5374c0cea4.zip"; sha512 = "5374c0cea4b0bbfdfae62da7bbdf1e1558d338335f4cacf2515c282ff358ff27b2ecb91ffa5330a8b14390ac66a1e146e10700440c1ab868208430f56b5f4d23"; };
"npmlog@npm:6.0.2" = { filename = "npmlog-npm-6.0.2-e0e69455c7-ae238cd264.zip"; sha512 = "ae238cd264a1c3f22091cdd9e2b106f684297d3c184f1146984ecbe18aaa86343953f26b9520dedd1b1372bc0316905b736c1932d778dbeb1fcf5a1001390e2a"; };
"ohmyfetch@npm:0.4.21" = { filename = "ohmyfetch-npm-0.4.21-24e4892090-28bc6dc507.zip"; sha512 = "28bc6dc507de37d2e818dc48a768716b24ef0d00830ea810f5d3d19e36f93d49281e91fe6a7b323555097fe0079b47c3bff05d736ea30445c3995dd5db43317b"; };
"once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
"onetime@npm:5.1.2" = { filename = "onetime-npm-5.1.2-3ed148fa42-2478859ef8.zip"; sha512 = "2478859ef817fc5d4e9c2f9e5728512ddd1dbc9fb7829ad263765bb6d3b91ce699d6e2332eef6b7dff183c2f490bd3349f1666427eaba4469fba0ac38dfd0d34"; };
"optionator@npm:0.9.1" = { filename = "optionator-npm-0.9.1-577e397aae-dbc6fa0656.zip"; sha512 = "dbc6fa065604b24ea57d734261914e697bd73b69eff7f18e967e8912aa2a40a19a9f599a507fa805be6c13c24c4eae8c71306c239d517d42d4c041c942f508a0"; };
"p-limit@npm:3.1.0" = { filename = "p-limit-npm-3.1.0-05d2ede37f-7c3690c4db.zip"; sha512 = "7c3690c4dbf62ef625671e20b7bdf1cbc9534e83352a2780f165b0d3ceba21907e77ad63401708145ca4e25bfc51636588d89a8c0aeb715e6c37d1c066430360"; };
"p-locate@npm:5.0.0" = { filename = "p-locate-npm-5.0.0-92cc7c7a3e-1623088f36.zip"; sha512 = "1623088f36cf1cbca58e9b61c4e62bf0c60a07af5ae1ca99a720837356b5b6c5ba3eb1b2127e47a06865fee59dd0453cad7cc844cda9d5a62ac1a5a51b7c86d3"; };
"p-map@npm:4.0.0" = { filename = "p-map-npm-4.0.0-4677ae07c7-cb0ab21ec0.zip"; sha512 = "cb0ab21ec0f32ddffd31dfc250e3afa61e103ef43d957cc45497afe37513634589316de4eb88abdfd969fe6410c22c0b93ab24328833b8eb1ccc087fc0442a1c"; };
"parent-module@npm:1.0.1" = { filename = "parent-module-npm-1.0.1-1fae11b095-6ba8b25514.zip"; sha512 = "6ba8b255145cae9470cf5551eb74be2d22281587af787a2626683a6c20fbb464978784661478dd2a3f1dad74d1e802d403e1b03c1a31fab310259eec8ac560ff"; };
"path-exists@npm:4.0.0" = { filename = "path-exists-npm-4.0.0-e9e4f63eb0-505807199d.zip"; sha512 = "505807199dfb7c50737b057dd8d351b82c033029ab94cb10a657609e00c1bc53b951cfdbccab8de04c5584d5eff31128ce6afd3db79281874a5ef2adbba55ed1"; };
"path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
"path-key@npm:3.1.1" = { filename = "path-key-npm-3.1.1-0e66ea8321-55cd7a9dd4.zip"; sha512 = "55cd7a9dd4b343412a8386a743f9c746ef196e57c823d90ca3ab917f90ab9f13dd0ded27252ba49dbdfcab2b091d998bc446f6220cd3cea65db407502a740020"; };
"path-parse@npm:1.0.7" = { filename = "path-parse-npm-1.0.7-09564527b7-49abf3d811.zip"; sha512 = "49abf3d81115642938a8700ec580da6e830dde670be21893c62f4e10bd7dd4c3742ddc603fe24f898cba7eb0c6bc1777f8d9ac14185d34540c6d4d80cd9cae8a"; };
"path-type@npm:4.0.0" = { filename = "path-type-npm-4.0.0-10d47fc86a-5b1e2daa24.zip"; sha512 = "5b1e2daa247062061325b8fdbfd1fb56dde0a448fb1455453276ea18c60685bdad23a445dc148cf87bc216be1573357509b7d4060494a6fd768c7efad833ee45"; };
"pathe@npm:0.3.9" = { filename = "pathe-npm-0.3.9-e2c03303d1-9afcbaa79c.zip"; sha512 = "9afcbaa79c5f8ec603b6b0a20b9accfcec8de57e26738f4a844de4625cfb07cc733b7234387ef42c7ab23a49b91846b6b51cb247584793842a3179539af463df"; };
"pathe@npm:1.0.0" = { filename = "pathe-npm-1.0.0-12bb397fc8-7b71a4930a.zip"; sha512 = "7b71a4930a5b46111c92149632f74b0e87bade3eabe6c9168dcc4846857a4e124eacc0c2bf044fe0d2a8b7f87ae62b9b2cb11938c61899d485cc36dd1a243a23"; };
"perfect-debounce@npm:0.1.3" = { filename = "perfect-debounce-npm-0.1.3-1fb57eeeee-c77465eb23.zip"; sha512 = "c77465eb23d87669e5ee646d12331507c45278e0f2e6fc20a587104b956c1a53f9afe723915d882f73fa588e42770a2edd2bbd93eb0b958c9ff1eb7b915ccdc1"; };
"picocolors@npm:1.0.0" = { filename = "picocolors-npm-1.0.0-d81e0b1927-a2e8092dd8.zip"; sha512 = "a2e8092dd86c8396bdba9f2b5481032848525b3dc295ce9b57896f931e63fc16f79805144321f72976383fc249584672a75cc18d6777c6b757603f372f745981"; };
"picomatch@npm:2.3.1" = { filename = "picomatch-npm-2.3.1-c782cfd986-050c865ce8.zip"; sha512 = "050c865ce81119c4822c45d3c84f1ced46f93a0126febae20737bd05ca20589c564d6e9226977df859ed5e03dc73f02584a2b0faad36e896936238238b0446cf"; };
"postcss@npm:8.4.20" = { filename = "postcss-npm-8.4.20-b87cd5ecc8-1a5609ea1c.zip"; sha512 = "1a5609ea1c1b204f9c2974a0019ae9eef2d99bf645c2c9aac675166c4cb1005be7b5e2ba196160bc771f5d9ac896ed883f236f888c891e835e59d28fff6651aa"; };
"prelude-ls@npm:1.2.1" = { filename = "prelude-ls-npm-1.2.1-3e4d272a55-cd192ec0d0.zip"; sha512 = "cd192ec0d0a8e4c6da3bb80e4f62afe336df3f76271ac6deb0e6a36187133b6073a19e9727a1ff108cd8b9982e4768850d413baa71214dd80c7979617dca827a"; };
"prettier-plugin-svelte@npm:2.9.0" = { filename = "prettier-plugin-svelte-npm-2.9.0-1562abe21c-2d74a96078.zip"; sha512 = "2d74a960783a1974a4818ebac25145ee26095c5652a777584b7eb8f08907702160263538396c03dce7f9bcd5b313f914b234eb809ccc1550a5933fc5e919ca88"; };
"prettier@npm:2.8.1" = { filename = "prettier-npm-2.8.1-be60b51821-4f21a0f126.zip"; sha512 = "4f21a0f1269f76fb36f54e9a8a1ea4c11e27478958bf860661fb4b6d7ac69aac1581f8724fa98ea3585e56d42a2ea317a17ff6e3324f40cb11ff9e20b73785cc"; };
"promise-inflight@npm:1.0.1" = { filename = "promise-inflight-npm-1.0.1-5bb925afac-2274948309.zip"; sha512 = "22749483091d2c594261517f4f80e05226d4d5ecc1fc917e1886929da56e22b5718b7f2a75f3807e7a7d471bc3be2907fe92e6e8f373ddf5c64bae35b5af3981"; };
"promise-retry@npm:2.0.1" = { filename = "promise-retry-npm-2.0.1-871f0b01b7-f96a3f6d90.zip"; sha512 = "f96a3f6d90b92b568a26f71e966cbbc0f63ab85ea6ff6c81284dc869b41510e6cdef99b6b65f9030f0db422bf7c96652a3fff9f2e8fb4a0f069d8f4430359429"; };
"punycode@npm:2.1.1" = { filename = "punycode-npm-2.1.1-26eb3e15cf-823bf443c6.zip"; sha512 = "823bf443c6dd14f669984dea25757b37993f67e8d94698996064035edd43bed8a5a17a9f12e439c2b35df1078c6bec05a6c86e336209eb1061e8025c481168e8"; };
"queue-microtask@npm:1.2.3" = { filename = "queue-microtask-npm-1.2.3-fcc98e4e2d-b676f8c040.zip"; sha512 = "b676f8c040cdc5b12723ad2f91414d267605b26419d5c821ff03befa817ddd10e238d22b25d604920340fd73efd8ba795465a0377c4adf45a4a41e4234e42dc4"; };
"readable-stream@npm:3.6.0" = { filename = "readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip"; sha512 = "d4ea81502d3799439bb955a3a5d1d808592cf3133350ed352aeaa499647858b27b1c4013984900238b0873ec8d0d8defce72469fb7a83e61d53f5ad61cb80dc8"; };
"readdirp@npm:3.6.0" = { filename = "readdirp-npm-3.6.0-f950cc74ab-1ced032e6e.zip"; sha512 = "1ced032e6e45670b6d7352d71d21ce7edf7b9b928494dcaba6f11fba63180d9da6cd7061ebc34175ffda6ff529f481818c962952004d273178acd70f7059b320"; };
"regexpp@npm:3.2.0" = { filename = "regexpp-npm-3.2.0-2513f32cfc-a78dc5c715.zip"; sha512 = "a78dc5c7158ad9ddcfe01aa9144f46e192ddbfa7b263895a70a5c6c73edd9ce85faf7c0430e59ac38839e1734e275b9c3de5c57ee3ab6edc0e0b1bdebefccef8"; };
"resolve-from@npm:4.0.0" = { filename = "resolve-from-npm-4.0.0-f758ec21bf-f4ba0b8494.zip"; sha512 = "f4ba0b8494846a5066328ad33ef8ac173801a51739eb4d63408c847da9a2e1c1de1e6cbbf72699211f3d13f8fc1325648b169bd15eb7da35688e30a5fb0e4a7f"; };
"resolve@npm:1.22.1" = { filename = "resolve-npm-1.22.1-3980488690-07af5fc1e8.zip"; sha512 = "07af5fc1e81aa1d866cbc9e9460fbb67318a10fa3c4deadc35c3ad8a898ee9a71a86a65e4755ac3195e0ea0cfbe201eb323ebe655ce90526fd61917313a34e4e"; };
"resolve@patch:resolve@npm%3A1.22.1#~builtin<compat/resolve>::version=1.22.1&hash=c3c19d" = { filename = "resolve-patch-0c52e0e4f7-5656f4d0be.zip"; sha512 = "5656f4d0bedcf8eb52685c1abdf8fbe73a1603bb1160a24d716e27a57f6cecbe2432ff9c89c2bd57542c3a7b9d14b1882b73bfe2e9d7849c9a4c0b8b39f02b8b"; };
"retry@npm:0.12.0" = { filename = "retry-npm-0.12.0-72ac7fb4cc-623bd7d2e5.zip"; sha512 = "623bd7d2e5119467ba66202d733ec3c2e2e26568074923bc0585b6b99db14f357e79bdedb63cab56cec47491c4a0da7e6021a7465ca6dc4f481d3898fdd3158c"; };
"reusify@npm:1.0.4" = { filename = "reusify-npm-1.0.4-95ac4aec11-c3076ebcc2.zip"; sha512 = "c3076ebcc22a6bc252cb0b9c77561795256c22b757f40c0d8110b1300723f15ec0fc8685e8d4ea6d7666f36c79ccc793b1939c748bf36f18f542744a4e379fcc"; };
"rimraf@npm:2.7.1" = { filename = "rimraf-npm-2.7.1-9a71f3cc37-cdc7f6eacb.zip"; sha512 = "cdc7f6eacb17927f2a075117a823e1c5951792c6498ebcce81ca8203454a811d4cf8900314154d3259bb8f0b42ab17f67396a8694a54cae3283326e57ad250cd"; };
"rimraf@npm:3.0.2" = { filename = "rimraf-npm-3.0.2-2cb7dac69a-87f4164e39.zip"; sha512 = "87f4164e396f0171b0a3386cc1877a817f572148ee13a7e113b238e48e8a9f2f31d009a92ec38a591ff1567d9662c6b67fd8818a2dbbaed74bc26a87a2a4a9a0"; };
"rollup@npm:3.7.4" = { filename = "rollup-npm-3.7.4-89fe7ffbe1-0f2478d740.zip"; sha512 = "0f2478d740527cdc8f4d81a5676221b0ec9495147cae0e6643627f6ac3ac63bf92385e26936ed8ef9ed06678a2ff7d8398489a235581c590f149149a003870d8"; };
"run-parallel@npm:1.2.0" = { filename = "run-parallel-npm-1.2.0-3f47ff2034-cb4f97ad25.zip"; sha512 = "cb4f97ad25a75ebc11a8ef4e33bb962f8af8516bb2001082ceabd8902e15b98f4b84b4f8a9b222e5d57fc3bd1379c483886ed4619367a7680dad65316993021d"; };
"sade@npm:1.8.1" = { filename = "sade-npm-1.8.1-4759dc74c1-0756e5b04c.zip"; sha512 = "0756e5b04c51ccdc8221ebffd1548d0ce5a783a44a0fa9017a026659b97d632913e78f7dca59f2496aa996a0be0b0c322afd87ca72ccd909406f49dbffa0f45d"; };
"safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
"safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
"sander@npm:0.5.1" = { filename = "sander-npm-0.5.1-860361072d-76da5b91dd.zip"; sha512 = "76da5b91dd7848de0c985adf035fc39ca76a3cd15d68bdae0a4672659a4bdef7b716747b31245af5dd769f19765a9e8e16ad577984b12cc041bdb09599921f3a"; };
"semver@npm:7.3.8" = { filename = "semver-npm-7.3.8-25a996cb4f-ba9c7cbbf2.zip"; sha512 = "ba9c7cbbf2b7884696523450a61fee1a09930d888b7a8d7579025ad93d459b2d1949ee5bbfeb188b2be5f4ac163544c5e98491ad6152df34154feebc2cc337c1"; };
"set-blocking@npm:2.0.0" = { filename = "set-blocking-npm-2.0.0-49e2cffa24-6e65a05f7c.zip"; sha512 = "6e65a05f7cf7ebdf8b7c75b101e18c0b7e3dff4940d480efed8aad3a36a4005140b660fa1d804cb8bce911cac290441dc728084a30504d3516ac2ff7ad607b02"; };
"set-cookie-parser@npm:2.5.1" = { filename = "set-cookie-parser-npm-2.5.1-530f8bd9ef-b99c37f976.zip"; sha512 = "b99c37f976e68ae6eb7c758bf2bbce1e60bb54e3eccedaa25f2da45b77b9cab58d90674cf9edd7aead6fbeac6308f2eb48713320a47ca120d0e838d0194513b6"; };
"shebang-command@npm:2.0.0" = { filename = "shebang-command-npm-2.0.0-eb2b01921d-6b52fe8727.zip"; sha512 = "6b52fe87271c12968f6a054e60f6bde5f0f3d2db483a1e5c3e12d657c488a15474121a1d55cd958f6df026a54374ec38a4a963988c213b7570e1d51575cea7fa"; };
"shebang-regex@npm:3.0.0" = { filename = "shebang-regex-npm-3.0.0-899a0cd65e-1a2bcae50d.zip"; sha512 = "1a2bcae50de99034fcd92ad4212d8e01eedf52c7ec7830eedcf886622804fe36884278f2be8be0ea5fde3fd1c23911643a4e0f726c8685b61871c8908af01222"; };
"signal-exit@npm:3.0.7" = { filename = "signal-exit-npm-3.0.7-bd270458a3-a2f098f247.zip"; sha512 = "a2f098f247adc367dffc27845853e9959b9e88b01cb301658cfe4194352d8d2bb32e18467c786a7fe15f1d44b233ea35633d076d5e737870b7139949d1ab6318"; };
"sirv@npm:2.0.2" = { filename = "sirv-npm-2.0.2-e19a876fae-6982f8ecee.zip"; sha512 = "6982f8ecee9392d246d7eeea8144e50334fe1b46a4fa942995a844ea88c2d518b17cce781bb09926c9a5692a7002a207d18dfd67af2aa538a15e733dc2042298"; };
"slash@npm:3.0.0" = { filename = "slash-npm-3.0.0-b87de2279a-94a93fff61.zip"; sha512 = "94a93fff615f25a999ad4b83c9d5e257a7280c90a32a7cb8b4a87996e4babf322e469c42b7f649fd5796edd8687652f3fb452a86dc97a816f01113183393f11c"; };
"smart-buffer@npm:4.2.0" = { filename = "smart-buffer-npm-4.2.0-5ac3f668bb-b5167a7142.zip"; sha512 = "b5167a7142c1da704c0e3af85c402002b597081dd9575031a90b4f229ca5678e9a36e8a374f1814c8156a725d17008ae3bde63b92f9cfd132526379e580bec8b"; };
"socks-proxy-agent@npm:7.0.0" = { filename = "socks-proxy-agent-npm-7.0.0-7aacf32ea0-7205543701.zip"; sha512 = "720554370154cbc979e2e9ce6a6ec6ced205d02757d8f5d93fe95adae454fc187a5cbfc6b022afab850a5ce9b4c7d73e0f98e381879cf45f66317a4895953846"; };
"socks@npm:2.7.1" = { filename = "socks-npm-2.7.1-17f2b53052-259d9e3e8e.zip"; sha512 = "259d9e3e8e1c9809a7f5c32238c3d4d2a36b39b83851d0f573bfde5f21c4b1288417ce1af06af1452569cd1eb0841169afd4998f0e04ba04656f6b7f0e46d748"; };
"sorcery@npm:0.10.0" = { filename = "sorcery-npm-0.10.0-10068608ec-e23fc06336.zip"; sha512 = "e23fc06336c6e47274bd5e23849f8a7a40071d06a6fe1105f2557eb8613563b4c867230fd5f7b143e86a9bf45f62279e39ce68545482821d7b51b185133f2bc9"; };
"source-map-js@npm:1.0.2" = { filename = "source-map-js-npm-1.0.2-ee4f9f9b30-c049a7fc4d.zip"; sha512 = "c049a7fc4deb9a7e9b481ae3d424cc793cb4845daa690bc5a05d428bf41bf231ced49b4cf0c9e77f9d42fdb3d20d6187619fc586605f5eabe995a316da8d377c"; };
"sourcemap-codec@npm:1.4.8" = { filename = "sourcemap-codec-npm-1.4.8-3a1a9e60b1-b57981c056.zip"; sha512 = "b57981c05611afef31605732b598ccf65124a9fcb03b833532659ac4d29ac0f7bfacbc0d6c5a28a03e84c7510e7e556d758d0bb57786e214660016fb94279316"; };
"ssri@npm:9.0.1" = { filename = "ssri-npm-9.0.1-33ce27f4f8-fb58f5e46b.zip"; sha512 = "fb58f5e46b6923ae67b87ad5ef1c5ab6d427a17db0bead84570c2df3cd50b4ceb880ebdba2d60726588272890bae842a744e1ecce5bd2a2a582fccd5068309eb"; };
"streamsearch@npm:1.1.0" = { filename = "streamsearch-npm-1.1.0-fc3ad6536d-1cce16cea8.zip"; sha512 = "1cce16cea8405d7a233d32ca5e00a00169cc0e19fbc02aa839959985f267335d435c07f96e5e0edd0eadc6d39c98d5435fb5bbbdefc62c41834eadc5622ad942"; };
"string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
"string_decoder@npm:1.3.0" = { filename = "string_decoder-npm-1.3.0-2422117fd0-8417646695.zip"; sha512 = "8417646695a66e73aefc4420eb3b84cc9ffd89572861fe004e6aeb13c7bc00e2f616247505d2dbbef24247c372f70268f594af7126f43548565c68c117bdeb56"; };
"strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
"strip-final-newline@npm:2.0.0" = { filename = "strip-final-newline-npm-2.0.0-340c4f7c66-69412b5e25.zip"; sha512 = "69412b5e25731e1938184b5d489c32e340605bb611d6140344abc3421b7f3c6f9984b21dff296dfcf056681b82caa3bb4cc996a965ce37bcfad663e92eae9c64"; };
"strip-indent@npm:3.0.0" = { filename = "strip-indent-npm-3.0.0-519e75a28d-18f045d57d.zip"; sha512 = "18f045d57d9d0d90cd16f72b2313d6364fd2cb4bf85b9f593523ad431c8720011a4d5f08b6591c9d580f446e78855c5334a30fb91aa1560f5d9f95ed1b4a0530"; };
"strip-json-comments@npm:3.1.1" = { filename = "strip-json-comments-npm-3.1.1-dcb2324823-492f73e272.zip"; sha512 = "492f73e27268f9b1c122733f28ecb0e7e8d8a531a6662efbd08e22cccb3f9475e90a1b82cab06a392f6afae6d2de636f977e231296400d0ec5304ba70f166443"; };
"supports-color@npm:7.2.0" = { filename = "supports-color-npm-7.2.0-606bfcf7da-3dda818de0.zip"; sha512 = "3dda818de06ebbe5b9653e07842d9479f3555ebc77e9a0280caf5a14fb877ffee9ed57007c3b78f5a6324b8dbeec648d9e97a24e2ed9fdb81ddc69ea07100f4a"; };
"supports-preserve-symlinks-flag@npm:1.0.0" = { filename = "supports-preserve-symlinks-flag-npm-1.0.0-f17c4d0028-53b1e247e6.zip"; sha512 = "53b1e247e68e05db7b3808b99b892bd36fb096e6fba213a06da7fab22045e97597db425c724f2bbd6c99a3c295e1e73f3e4de78592289f38431049e1277ca0ae"; };
"svelte-check@npm:2.10.2" = { filename = "svelte-check-npm-2.10.2-a924fed3b4-687274f092.zip"; sha512 = "687274f0926e5dc240edfe65fbdd70168c0fc750126b0021a375749c8a6abc0d08c7965e794362aa6bea1a49d11bc914aca97fdf78ae0bcc99c78d3e560ff726"; };
"svelte-headless-table@npm:0.15.3" = { filename = "svelte-headless-table-npm-0.15.3-01921ca2aa-101d3365bb.zip"; sha512 = "101d3365bb09c60f13f225947bb965626a32ae276f6463fc3b6a138094f9899767c01772970dea2195fd09299b802480758f034fa6ec52bd89378c9681d4431b"; };
"svelte-hmr@npm:0.15.1" = { filename = "svelte-hmr-npm-0.15.1-6d627a3716-af2e5c356e.zip"; sha512 = "af2e5c356ed6467d6567ce1b908bc077c9d08a89f3ffda81e63989c1c3f374a88b1b67453e86e3674320aa10e7cdf42a10dc551900997b627b4702db447f2bf3"; };
"svelte-keyed@npm:1.1.6" = { filename = "svelte-keyed-npm-1.1.6-512eed4966-54af113088.zip"; sha512 = "54af1130885e7f73100db38cfd6bcdcaccd9ddeee1a063fba64b3506fa14c0047e922f7eb659e82309bedbca8680b5e329eeedaed607596f60b1aea5ca791e5f"; };
"svelte-preprocess@npm:4.10.7" = { filename = "svelte-preprocess-npm-4.10.7-d83f53f087-51a0820c14.zip"; sha512 = "51a0820c14bcc411ddf3b1cf4c772e73873626ed0b6c54dfca9e06bd6a6b22c9502436df3f1a4dab9eb3a404bba95002fd70cadea29a84fc36da3071309a8b91"; };
"svelte-preprocess@npm:5.0.0" = { filename = "svelte-preprocess-npm-5.0.0-b1f1b1e27a-ef70e62869.zip"; sha512 = "ef70e6286942d291f6063e3aa10f2f00e33fc36a5fbee765c4abfbfc01a817ceaf6a395d0b4ad163c5849aceea027dfc181f50205bd53772444781a41cec8e38"; };
"svelte-render@npm:1.5.0" = { filename = "svelte-render-npm-1.5.0-bd97d3d003-92094d6dbc.zip"; sha512 = "92094d6dbc76186f2e2233907735d0fdd1a7482745638a07efffe65e795242bad75dbaabe67072ca1c41fd0f837fc22e1eb7d8b15887aafb3c8bd51aead6ea53"; };
"svelte-subscribe@npm:1.0.5" = { filename = "svelte-subscribe-npm-1.0.5-0fb762a298-b3d7974129.zip"; sha512 = "b3d7974129ea86aa3c35889dde593e133ac5bb30d0ca59da09166d25d730325e7b89244bc715303c3a048cf9f166727eccfa79b07b0725d41d5e63326bfcf20d"; };
"svelte@npm:3.55.0" = { filename = "svelte-npm-3.55.0-fbeb605f72-0b182973a4.zip"; sha512 = "0b182973a4152fec8baa59cc168ca4528d63faba130bc83063a7d55d1732a81303b48745f4bffe53436b875b9c98960b0265d45473e5b3d25c77b116fdc274f0"; };
"tar@npm:6.1.13" = { filename = "tar-npm-6.1.13-3234e72781-8a278bed12.zip"; sha512 = "8a278bed123aa9f53549b256a36b719e317c8b96fe86a63406f3c62887f78267cea9b22dc6f7007009738509800d4a4dccc444abd71d762287c90f35b002eb1c"; };
"text-table@npm:0.2.0" = { filename = "text-table-npm-0.2.0-d92a778b59-b6937a38c8.zip"; sha512 = "b6937a38c80c7f84d9c11dd75e49d5c44f71d95e810a3250bd1f1797fc7117c57698204adf676b71497acc205d769d65c16ae8fa10afad832ae1322630aef10a"; };
"tiny-glob@npm:0.2.9" = { filename = "tiny-glob-npm-0.2.9-068f4ab3f8-aea5801eb6.zip"; sha512 = "aea5801eb6663ddf77ebb74900b8f8bd9dfcfc9b6a1cc8018cb7421590c00bf446109ff45e4b64a98e6c95ddb1255a337a5d488fb6311930e2a95334151ec9c6"; };
"to-regex-range@npm:5.0.1" = { filename = "to-regex-range-npm-5.0.1-f1e8263b00-f76fa01b3d.zip"; sha512 = "f76fa01b3d5be85db6a2a143e24df9f60dd047d151062d0ba3df62953f2f697b16fe5dad9b0ac6191c7efc7b1d9dcaa4b768174b7b29da89d4428e64bc0a20ed"; };
"totalist@npm:3.0.0" = { filename = "totalist-npm-3.0.0-60426683c2-ec499bddfc.zip"; sha512 = "ec499bddfc73d5b6c73f8ff68afd7bed286705797f928a11177fee5d1ee80e9052ffcb434638437702e16864bd5490f437a54f79bfea9564e875d34ed3254bca"; };
"tslib@npm:1.14.1" = { filename = "tslib-npm-1.14.1-102499115e-dbe628ef87.zip"; sha512 = "dbe628ef87f66691d5d2959b3e41b9ca0045c3ee3c7c7b906cc1e328b39f199bb1ad9e671c39025bd56122ac57dfbf7385a94843b1cc07c60a4db74795829acd"; };
"tslib@npm:2.4.1" = { filename = "tslib-npm-2.4.1-36f0ed04db-19480d6e03.zip"; sha512 = "19480d6e0313292bd6505d4efe096a6b31c70e21cf08b5febf4da62e95c265c8f571f7b36fcc3d1a17e068032f59c269fab3459d6cd3ed6949eafecf64315fca"; };
"tsutils@npm:3.21.0" = { filename = "tsutils-npm-3.21.0-347e6636c5-1843f4c1b2.zip"; sha512 = "1843f4c1b2e0f975e08c4c21caa4af4f7f65a12ac1b81b3b8489366826259323feb3fc7a243123453d2d1a02314205a7634e048d4a8009921da19f99755cdc48"; };
"type-check@npm:0.4.0" = { filename = "type-check-npm-0.4.0-60565800ce-ec688ebfc9.zip"; sha512 = "ec688ebfc9c45d0c30412e41ca9c0cdbd704580eb3a9ccf07b9b576094d7b86a012baebc95681999dd38f4f444afd28504cb3a89f2ef16b31d4ab61a0739025a"; };
"type-fest@npm:0.20.2" = { filename = "type-fest-npm-0.20.2-b36432617f-4fb3272df2.zip"; sha512 = "4fb3272df21ad1c552486f8a2f8e115c09a521ad7a8db3d56d53718d0c907b62c6e9141ba5f584af3f6830d0872c521357e512381f24f7c44acae583ad517d73"; };
"typescript@npm:4.9.4" = { filename = "typescript-npm-4.9.4-51bdca3293-e782fb9e00.zip"; sha512 = "e782fb9e0031cb258a80000f6c13530288c6d63f1177ed43f770533fdc15740d271554cdae86701c1dd2c83b082cea808b07e97fd68b38a172a83dbf9e0d0ef9"; };
"typescript@patch:typescript@npm%3A4.9.4#~builtin<compat/typescript>::version=4.9.4&hash=d73830" = { filename = "typescript-patch-b74a6ef84c-37f6e2c3c5.zip"; sha512 = "37f6e2c3c5e2aa5934b85b0fddbf32eeac8b1bacf3a5b51d01946936d03f5377fe86255d4e5a4ae628fd0cd553386355ad362c57f13b4635064400f3e8e05b9d"; };
"ufo@npm:0.8.6" = { filename = "ufo-npm-0.8.6-4faa730f12-5d48357623.zip"; sha512 = "5d483576230c7bfa2c9c9e5d864995e18d6c08ee3955c2237cc1a0d4b35a52991a0f5d26fe8cbf11952109a925a88dc14d973e0d14159b5b96b0fe7393a52899"; };
"unconfig@npm:0.3.7" = { filename = "unconfig-npm-0.3.7-534443622d-d3bcd9a8d5.zip"; sha512 = "d3bcd9a8d5d97418e525aa879f09d0ddc5c97be4d6237ddc8f40fb5f1feeced2163a8f8ddfa925e45d28499a4b05d86a4f2aedb3385604888225589fbc0e2367"; };
"undici@npm:5.14.0" = { filename = "undici-npm-5.14.0-747f9fac1d-7a076e44d8.zip"; sha512 = "7a076e44d84b25844b4eb657034437b8b9bb91f17d347de474fdea1d4263ce7ae9406db79cd30de5642519277b4893f43073258bcc8fed420b295da3fdd11b26"; };
"unique-filename@npm:2.0.1" = { filename = "unique-filename-npm-2.0.1-183c6c7c2b-807acf3381.zip"; sha512 = "807acf3381aff319086b64dc7125a9a37c09c44af7620bd4f7f3247fcd5565660ac12d8b80534dcbfd067e6fe88a67e621386dd796a8af828d1337a8420a255f"; };
"unique-slug@npm:3.0.0" = { filename = "unique-slug-npm-3.0.0-0b82e51577-49f8d915ba.zip"; sha512 = "49f8d915ba7f0101801b922062ee46b7953256c93ceca74303bd8e6413ae10aa7e8216556b54dc5382895e8221d04f1efaf75f945c2e4a515b4139f77aa6640c"; };
"unocss@npm:0.47.6" = { filename = "unocss-npm-0.47.6-e0c423e997-bba09be42e.zip"; sha512 = "bba09be42e9cacf82b333a37577a43882edd5573c050a51204537d3dcb3bc58a56f7bb73d2ebb066830773c09ba015b56fbfe270fa95726f953f112c7ef6abc3"; };
"uri-js@npm:4.4.1" = { filename = "uri-js-npm-4.4.1-66d11cbcaf-7167432de6.zip"; sha512 = "7167432de6817fe8e9e0c9684f1d2de2bb688c94388f7569f7dbdb1587c9f4ca2a77962f134ec90be0cc4d004c939ff0d05acc9f34a0db39a3c797dada262633"; };
"util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
"vite@npm:4.0.1" = { filename = "vite-npm-4.0.1-899c18249b-c51bd7cb95.zip"; sha512 = "c51bd7cb955973cce1c63e6d29ac25ea6f8920db6de2ca97f285c80cf9607649d87254d1fabd9aa5920149572a6220686b9e3bf6fd0851f7c86ec8522bba0098"; };
"vitefu@npm:0.2.3" = { filename = "vitefu-npm-0.2.3-283ffc2ecd-d4b3b76cf4.zip"; sha512 = "d4b3b76cf4a6c8efd28df2a0c4c3a6ff8879397861ff812ec46cbd824b8dbf83b4aa8c0436505c404883df6c13ca67c2497f8140a4070fa8feeeaaf727b8654a"; };
"which@npm:2.0.2" = { filename = "which-npm-2.0.2-320ddf72f7-1a5c563d3c.zip"; sha512 = "1a5c563d3c1b52d5f893c8b61afe11abc3bab4afac492e8da5bde69d550de701cf9806235f20a47b5c8fa8a1d6a9135841de2596535e998027a54589000e66d1"; };
"wide-align@npm:1.1.5" = { filename = "wide-align-npm-1.1.5-889d77e592-d5fc37cd56.zip"; sha512 = "d5fc37cd561f9daee3c80e03b92ed3e84d80dde3365a8767263d03dacfc8fa06b065ffe1df00d8c2a09f731482fcacae745abfbb478d4af36d0a891fad4834d3"; };
"word-wrap@npm:1.2.3" = { filename = "word-wrap-npm-1.2.3-7fb15ab002-30b48f91fc.zip"; sha512 = "30b48f91fcf12106ed3186ae4fa86a6a1842416df425be7b60485de14bec665a54a68e4b5156647dec3a70f25e84d270ca8bc8cd23182ed095f5c7206a938c1f"; };
"wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
"yallist@npm:4.0.0" = { filename = "yallist-npm-4.0.0-b493d9e907-343617202a.zip"; sha512 = "343617202af32df2a15a3be36a5a8c0c8545208f3d3dfbc6bb7c3e3b7e8c6f8e7485432e4f3b88da3031a6e20afa7c711eded32ddfb122896ac5d914e75848d5"; };
"yocto-queue@npm:0.1.0" = { filename = "yocto-queue-npm-0.1.0-c6c9a7db29-f77b3d8d00.zip"; sha512 = "f77b3d8d00310def622123df93d4ee654fc6a0096182af8bd60679ddcdfb3474c56c6c7190817c84a2785648cdee9d721c0154eb45698c62176c322fb46fc700"; };
};

in optionalOverride overrideAttrs project
