[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tenzir-cli"
version = "5.19.0"
description = "Tenzir CLI bindings and binary launchers"
requires-python = ">=3.9"
license = { text = "BSD-3-Clause" }
authors = [
  { name = "Tenzir", email = "engineering@tenzir.com" },
]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Plugins",
    "License :: OSI Approved :: BSD License",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: POSIX :: Linux",
    "Topic :: Security",
    "Topic :: Scientific/Engineering :: Information Analysis",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Software Development :: Object Brokering",
    "Topic :: System :: Distributed Computing",
]
dependencies = [
  "tenzir-core>=5.19.0,<5.20.0",
]

[project.optional-dependencies]
module = ["numpy>=1.24,<3.0"]
operator = [
  "tenzir-operators[pandas]>=5.19.0,<5.20.0",
  "aiohttp>=3.8,<4.0",
]

[project.scripts]
tenzir = "tenzir._bin.tenzir:main"
tenzir-ctl = "tenzir._bin.tenzir_ctl:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"tenzir" = [
  "bin/**",
  "libexec/**",
  "share/**",
]
