#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    if dpkg-statoverride --list /var/lib/tenzir >/dev/null 2>&1 ; then
        dpkg-statoverride --remove /var/lib/tenzir
    fi
    echo "Removing tenzir state directory (/var/lib/tenzir)"
    rm -rf /var/lib/tenzir

     if dpkg-statoverride --list /var/log/tenzir >/dev/null 2>&1 ; then
        dpkg-statoverride --remove /var/log/tenzir
    fi
    echo "Removing tenzir log directory (/var/log/tenzir)"
    rm -rf /var/log/tenzir

    deluser  --system tenzir || echo "Could not remove tenzir user."

    echo "Removing tenzir from \$PATH"
    rm -f /etc/profile.d/tenzir.sh
fi

# Automatically added by dh_installsystemd/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'tenzir-node.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'tenzir-node.service' >/dev/null || true
		deb-systemd-helper unmask 'tenzir-node.service' >/dev/null || true
	fi
	rm -f /lib/systemd/system/tenzir-node.service
fi
# End automatically added section
