#!/bin/sh

set -e

if [ "$1" = "purge" ] ; then
    if dpkg-statoverride --list /var/lib/vast >/dev/null 2>&1 ; then
        dpkg-statoverride --remove /var/lib/vast
    fi
    echo "Removing VAST db directory (/var/lib/vast)"
    rm -rf /var/lib/vast

     if dpkg-statoverride --list /var/log/vast >/dev/null 2>&1 ; then
        dpkg-statoverride --remove /var/log/vast
    fi
    echo "Removing VAST log directory (/var/log/vast)"
    rm -rf /var/log/vast

    deluser  --system vast || echo "Could not remove VAST user."
fi

# Automatically added by dh_installsystemd/13.3.4
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.3.4
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'vast.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'vast.service' >/dev/null || true
		deb-systemd-helper unmask 'vast.service' >/dev/null || true
	fi
	rm -f /lib/systemd/system/vast.service
fi
# End automatically added section
