#! /usr/bin/env bash
set -eux -o pipefail

build=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      >&2 echo "Execute tests for Tenzir's Docker Compose files."
      >&2 echo "NOTE: By default, attempts to pull images rather than building."
      >&2 echo ""
      >&2 echo "USAGE: ${0} [--build] [-h|--help]"
      exit 0
      ;;
    --build)
      build=1
      shift 1
      ;;
    *)
      >&2 echo "unknown option: $1" >&2
      exit 1
      ;;
  esac
done

export COMPOSE_FILE="compose/tenzir.yaml"
if (( "${build}" == 1 )); then
  export TENZIR_CONTAINER_REGISTRY='docker.io'
  export TENZIR_CONTAINER_REF='latest'
  export COMPOSE_FILE="${COMPOSE_FILE}:compose/tenzir.build.yaml"
  build_policy='--pull=never'
else
  export TENZIR_CONTAINER_REGISTRY="${TENZIR_CONTAINER_REGISTRY:-ghcr.io}"
  export TENZIR_CONTAINER_REF="${TENZIR_CONTAINER_REF:-$(git rev-parse --abbrev-ref HEAD | sed -E 's/[^a-zA-Z0-9._-]+/-/g;s/^-*//')}"
  if [[ "${TENZIR_CONTAINER_REF}" == "main" ]]; then
    export TENZIR_CONTAINER_REF="$(git rev-parse HEAD)"
  fi
  build_policy='--pull=always'
fi

pushd "$(git -C "$(dirname "$(readlink -f "${0}")")" rev-parse --show-toplevel)/docker"

# Bring up the Docker Compose stack.
docker compose down --volumes
docker compose up ${build_policy} --detach

# Run a basic status check; we don't particularly care about the output itself,
# so essentially we're just checking for the exit code.
docker compose run tenzir status > /dev/null

# Ingest some test data.
gunzip -c ../tenzir/functional-test/data/zeek/*.log.gz |
  docker compose run --no-TTY tenzir import --blocking zeek
docker compose run --no-TTY tenzir import --blocking suricata \
  < ../tenzir/functional-test/data/suricata/eve.json

# Check whether we imported the right amount of data.
num_imported="$(docker compose run --interactive=false tenzir count)"
num_imported_expected="18494"
[[ "${num_imported}" == "${num_imported_expected}" ]]

# Print logs for easier debugging in case something went wrong.
docker compose ps
docker compose logs

# Assert that all containers that exited have exited cleanly.
docker compose ps --format json --all --status exited |
  jq -sre 'map(.ExitCode != 0) | index(false)'

docker compose down --volumes

popd
