.TH VAST 1 "November 03, 2015" 0.1 "Visibility Across Space and Time"
.SH NAME
.PP
\fB\fCvast\fR \-\- manage a VAST topology
.SH SYNOPSIS
.PP
\fB\fCvast\fR [\fIoptions\fP] \fIcommand\fP [\fIarguments\fP]
.SH OVERVIEW
.PP
VAST is a platform for network forensics. Similar to a datawarehouse, the
system archives large amounts of data and features a type\-safe query engine.
Internally, VAST exhibits a modular architecture implemented entirely in terms
of the actor model. In this model, concurrent entities (actors) execute in
parallel and communicate asynchronously solely via message passing. Users spawn
system components as actors on one or more nodes and connect them together to
create a custom topology.
.SH DESCRIPTION
.PP
The \fB\fCvast\fR executable enables users to manage a VAST topology: one or more
\fBnode\fPs run various components, such as event sources and sinks for data
import/export, issuing queries, or retrieving statistics about system
components. The following key actors exist:
.TP
\fBnode\fP
The main VAST actor which accommodates all other actors and manages global
state.
.TP
\fBsource\fP
Generates events from a data source, such as packets from a network interface
or log files.
.TP
\fBsink\fP
Receives events as the result of a query and displays them in specific output
format, such as JSON, PCAP (for packets), or Bro logs.
.TP
\fBarchive\fP
Compressed bulk storage of the all events.
.TP
\fBindex\fP
Accelerates queries by constructing bitmap indexes over a subset of the event
data.
.TP
\fBimporter\fP
Accepts events from \fBsource\fPs, assigns them unique 64\-bit IDs, and relays
them to \fBarchive\fP and \fBindex\fP\&.
.TP
\fBexporter\fP
Accepts query expressions from users, asks \fBindex\fP for hits, takes them to
\fBarchive\fP to extract candidates, and relays matching events to \fBsink\fPs.
.PP
The \fB\fCvast\fR executable spawns \fBnode\fP, which acts as a container for other
actors. Typically, each physical machine in a VAST deployment runs a single
\fB\fCvast\fR process. For single\-machine deployments all actors run inside this
process, whereas cluster deployments consist of multiple nodes with actors
spread across them.
.PP
Nodes can enter a peering relationship and build a topology. All peers have
the same authority: if one fails, others can take over. By default, each
node includes all core actors: \fBarchive\fP, \fBindex\fP, \fBimporter\fP\&. For
more fine\-grained control about the components running on a node, one can spawn
the node in "bare" mode to get an empty container. This allows for more
flexible arrangement of components to best match the available system hardware.
.SH OPTIONS
.PP
The \fIoptions\fP in front of \fIcommand\fP control how to to connect to a node.
.PP
The following \fIoptions\fP are available:
.TP
\fB\fC\-d\fR \fIdir\fP [\fI\&.\fP]
The directory for logs and state.
.TP
\fB\fC\-e\fR \fIendpoint\fP [\fI127.0.0.1:42000\fP]
The endpoint of the node to connect to or launch. (See below)
.TP
\fB\fC\-h\fR
Display a help message and exit.
.TP
\fB\fC\-l\fR \fIverbosity\fP [\fI3\fP]
The logging verbosity. (See below)
.TP
\fB\fC\-m\fR \fImessages\fP [\fI\-1\fP]
The CAF worker throughput expressed in the maximum number of messages to
process when a worker gets scheduled. The default value of \fI\-1\fP means an
unlimited number of messages.
.TP
\fB\fC\-n\fR
Do not attempt to connect to a remote \fBnode\fP but start a local instance
instead.
.TP
\fB\fC\-p\fR \fIlogfile\fP
Enable CAF profiling of worker threads and actors and write the per\-second
sampled data to \fIlogfile\fP\&.
.TP
\fB\fC\-t\fR \fIthreads\fP [\fIstd::thread::hardware_concurrency()\fP]
The number of worker threads to use for CAF's scheduler.
.TP
\fB\fC\-v\fR
Print VAST version and exit.
.PP
When specifying an endpoint via \fB\fC\-e\fR, \fB\fCvast\fR connects to that endpoint to
obtain a \fBnode\fP reference. An exception is the command \fB\fCvast start\fR,
which uses the endpoint specification to spawn a \fBnode\fP\&.
.SS endpoint
.PP
An endpoint has the format \fIhost:port\fP where \fIhost\fP is a hostname or IP address
and \fIport\fP the transport\-layer port of the listening daemon. Either can be
omitted: \fIhost\fP or \fI:port\fP are also valid endpoints. IPv6 addresses must be
enclosed in brackets in conjunction with a \fIport\fP, e.g., \fI[::1]:42001\fP\&.
.SS verbosity
.PP
The verbosity controls the amount of status messages displayed on console and
in log files. It can take on the following values:
    \fI0\fP \fI(quiet)\fP: do not produce any output
    \fI1\fP \fI(error)\fP: report failures which constitute a program error
    \fI2\fP \fI(warn)\fP: notable issues that do not affect correctness
    \fI3\fP \fI(info)\fP: status messages representing system activity
    \fI4\fP \fI(verbose)\fP: more fine\-grained activity reports
    \fI5\fP \fI(debug)\fP: copious low\-level implementation details
    \fI6\fP \fI(trace)\fP: log function entry and exit
.SH COMMANDS
.PP
This section describes each \fIcommand\fP and its \fIarguments\fP\&. The following
commands exist:
    \fIstart\fP         starts a node
    \fIstop\fP          stops a node
    \fIpeer\fP          peers with another node
    \fIshow\fP          shows various properties of a topology
    \fIspawn\fP         creates a new actor
    \fIquit\fP          terminates an actor
    \fIsend\fP          send a message to an actor
    \fIconnect\fP       connects two spawned actors
    \fIdisconnect\fP    disconnects two connected actors
    \fIimport\fP        imports data from standard input
    \fIexport\fP        exports query results to standard output
.SS start
.PP
Synopsis:
.IP
\fIstart\fP [\fIarguments\fP]
.PP
Start a node at the specified endpoint.
.PP
Available \fIarguments\fP:
.TP
\fB\fC\-b\fR
Run in \fIbare\fP mode, i.e., do not spawn any actors. Use \fIbare\fP mode when you
want to create a custom topology. When not specifying this option, \fB\fCvast\fR
automatically spawns all core actors by executing the following commands
upon spawning the node:
.PP
.RS
.nf
  vast spawn identifier
  vast spawn importer
  vast spawn archive
  vast spawn index
  vast connect importer identifier
  vast connect importer archive
  vast connect importer index
.fi
.RE
.TP
\fB\fC\-f\fR
Start in foreground, i.e., do not detach from controlling terminal and
run in background. Unless specified, VAST will call 
.BR daemon (3).
.TP
\fB\fC\-n\fR \fIname\fP [\fIhostname\fP]
Overrides the node \fIname\fP, which defaults to the system hostname. Each node
in a topology must have a unique name, otherwise peering fails.
.SS stop
.PP
Synopsis:
.IP
\fIstop\fP
.PP
Stops the node and terminates all contained actors.
.SS peer
.PP
Synopsis:
.IP
\fIpeer\fP \fIendpoint\fP
.PP
Joins a topology through a node identified by \fIendpoint\fP\&.
See \fBOPTIONS\fP for a description of the \fIendpoint\fP syntax.
.SS show
.PP
Synopsis:
.IP
\fIshow\fP \fIargument\fP
.PP
Shows various properties of a topology. \fIargument\fP can have the
following values:
.TP
\fInodes\fP
Displays all existing nodes in the topology.
.TP
\fIpeers\fP
Displays the nodes connected to this node.
.TP
\fIactors\fP
Displays the existing components per node.
.TP
\fItopology\fP
Displays the connections between nodes.
.SS spawn
.PP
Synopsis:
.IP
\fIspawn\fP [\fIarguments\fP] \fIactor\fP [\fIparameters\fP]
.PP
Creates a new actor of kind \fIactor\fP\&. Some actor types can have at most one
instance while others can have multiple instances.
.PP
Available \fIarguments\fP:
.TP
\fB\fC\-n\fR \fIname\fP
Controls the spawn location. If \fB\fC\-n\fR \fIname\fP is given, the actor will be
spawned on the node identified by \fIname\fP\&. Otherwise the actor will be
spawned on the connected node.
.PP
\fB\fC\-l\fR \fIlabel\fP
   A unique identifier for \fIactor\fP within a node. The default label
   has the form \fIactorN\fP where \fIN\fP is a running counter increased for each
   spawned instance of \fIactor\fP\&.
.PP
Available \fIactor\fP values with corresponding \fIparameters\fP:
.TP
\fIcore\fP
Spawns all \fIcore\fP actors (i.e., ARCHIVE, INDEX, IDENTIFIER, IMPORTER) and
connects IMPORTER with them.
.PP
\fIarchive\fP [\fIparameters\fP]
  \fB\fC\-c\fR \fIcompression\fP [\fIlz4\fP]
    Compression algorithm for chunks
  \fB\fC\-s\fR \fIsegments\fP [\fI10\fP]
    Number of cached segments
  \fB\fC\-m\fR \fIsize\fP [\fI128\fP]
    Maximum segment size in MB
.PP
\fIindex\fP [\fIparameters\fP]
  \fB\fC\-a\fR \fIpartitions\fP [\fI5\fP]
    Number of active partitions to load\-balance events over.
  \fB\fC\-p\fR \fIpartitions\fP [\fI10\fP]
    Number of passive partitions.
  \fB\fC\-e\fR \fIevents\fP [\fI1,048,576\fP]
    Maximum events per partition. When an active partition reaches its
    maximum, the index evicts it from memory and replaces it with an empty
    partition.
.PP
\fIimporter\fP
.PP
\fIexporter\fP [\fIparameters\fP] \fIexpression\fP
  \fB\fC\-a\fR
    Autoconnect to available archives and indexes on the node.
  \fB\fC\-c\fR
    Marks this exporter as \fIcontinuous\fP\&.
  \fB\fC\-h\fR
    Marks this exporter as \fIhistorical\fP\&.
  \fB\fC\-u\fR
    Marks this exporter as \fIunified\fP, which is equivalent to both
    \fB\fC\-c\fR and \fB\fC\-h\fR\&.
  \fB\fC\-e\fR \fIn\fP [\fI0\fP]
    The maximum number of events to extract; \fIn = 0\fP means unlimited.
.PP
\fIsource\fP \fBX\fP [\fIparameters\fP]
  \fBX\fP specifies the format of \fIsource\fP\&. Each source format has its own set of
  parameters, but the following parameters apply to all formats:
  \fB\fC\-a\fR
    Autoconnect to available importers on the node.
  \fB\fC\-b\fR \fIbatch\-size\fP [\fI100,000\fP]
    Number of events to read in one batch.
.PP
\fIsource\fP \fIbro\fP
  \fB\fC\-r\fR \fIpath\fP
    Name of the filesystem \fIpath\fP (file or directory) to read events from.
  \fB\fC\-s\fR \fIschema\fP
    Path to an alterative \fIschema\fP file which overrides the default attributes.
  \fB\fC\-u\fR \fIuds\fP
    Treats \fB\fC\-r\fR as a listening UNIX domain socket instead of a regular file.
.PP
\fIsource\fP \fIbgpdump\fP
  \fB\fC\-r\fR \fIpath\fP
    Name of the file to read events from.
  \fB\fC\-s\fR \fIschema\fP
    Path to an alterative \fIschema\fP file which overrides the default attributes.
  \fB\fC\-u\fR \fIuds\fP
    Treats \fB\fC\-r\fR as a listening UNIX domain socket instead of a regular file.
.PP
\fIsource\fP \fItest\fP [\fIparameters\fP]
  \fB\fC\-e\fR \fIevents\fP
    The maximum number of \fIevents\fP to generate.
.PP
\fIsource\fP \fIpcap\fP [\fIparameters\fP]
  \fB\fC\-i\fR \fIinterface\fP
    Name of the network \fIinterface\fP to read packets from. (Overrides \-r)
  \fB\fC\-c\fR \fIcutoff\fP
    The \fIcutoff\fP values specifies the maximum number of bytes to record per
    flow in each direction. That is, the maximum number of recorded bytes flow
    bytes can at most be twice as much as \fIcutoff\fP\&. the flow will be ignored
  \fB\fC\-f\fR \fImax\-flows\fP [\fI1,000,000\fP]
    The maximum number of flows to track concurrently. When there exist more
    flows than \fImax\-flows\fP, a new flow will cause eviction of a element from
    the flow table chosen uniformly at random.
  \fB\fC\-a\fR \fImax\-age\fP [\fI60\fP]
    The maximum lifetime of a flow before it gets evicted from the flow table.
  \fB\fC\-p\fR \fIc\fP
    Enable pseudo\-realtime mode by a factor of \fI1/c\fP to artificially delay
    packet processing when reading from trace files. This means that the PCAP
    source in that it sleeps for the amount of time observed in the packet
    timestamp differences. If the PCAP source encounters a packet \fIp1\fP after a
    previous packet \fIp0\fP with timestamps \fIt1\fP and \fIt0\fP, then it will sleep for
    time \fI(t1\-t0)/c\fP before processing \fIp1\fP\&.
  \fB\fC\-r\fR \fIpath\fP
    Filename of trace file to read packets from.
  \fB\fC\-s\fR \fIschema\fP
    Path to an alterative \fIschema\fP file which overrides the default attributes.
.PP
\fIsink\fP \fBX\fP [\fIparameters\fP]
  \fBX\fP specifies the format of \fIsink\fP\&. Each source format has its own set of
  parameters, but the following parameters apply to all formats:
  \fB\fC\-w\fR \fIpath\fP
    Name of the filesystem \fIpath\fP (file or directory) to write events to.
.PP
\fIsink\fP \fIascii\fP
  \fB\fC\-u\fR \fIuds\fP
    Treats \fB\fC\-w\fR as a listening UNIX domain socket instead of a regular file.
.PP
\fIsink\fP \fIbro\fP
.PP
\fIsink\fP \fIcsv\fP
.PP
\fIsink\fP \fIjson\fP
  \fB\fC\-u\fR \fIuds\fP
    Treats \fB\fC\-w\fR as a listening UNIX domain socket instead of a regular file.
.PP
\fIsink\fP \fIpcap\fP [\fIparameters\fP]
  \fB\fC\-f\fR \fIflush\fP [\fI1000\fP]
    Flush the output PCAP trace after having processed \fIflush\fP packets.
.PP
\fIprofiler\fP [\fIparameters\fP]
  If compiled with gperftools, enables the gperftools CPU or heap profiler to
  collect samples at a given resolution.
  \fB\fC\-c\fR
    Launch the CPU profiler.
  \fB\fC\-h\fR
    Launch the heap profiler.
  \fB\fC\-r\fR \fIseconds\fP [\fI1\fP]
    The profiling resolution in seconds.
.SS quit
.PP
Synopsis:
.IP
\fIquit\fP \fIname\fP
.PP
Terminates an actor. The argument \fIname\fP refers to an actor label.
.SS send
.PP
Synopsis:
.IP
\fIsend\fP \fIname\fP \fImessage\fP
.PP
Sends a message to an actor. The argument \fIname\fP refers to the actor to run.
The argument \fImessage\fP represents the data to send to the actor.
.PP
Available messages:
.TP
\fIrun\fP
Tells an actor to start operating. Most actors do not need to be told to run
explicitly. Only actors having a multi\-stage setup phase (e.g., sources and
exporters) can be run explicitly: after spawning one connects them with other
actors before they run in a fully operating state.
.TP
\fIflush\fP
Tells an actor to flush its state to the file system.
.SS connect
.PP
Synopsis:
.IP
\fIconnect\fP \fIA\fP \fIB\fP
.PP
Connects two actors named \fIA\fP and \fIB\fP by registering \fIA\fP as source for \fIB\fP and
\fIB\fP as sink for \fIA\fP\&.
.PP
Both \fIA\fP and \fIB\fP can consist of a comma\-separated lists of actor labels. That
is, if \fIA\fP consists of \fIn\fP list entries and \fIB\fP of \fIm\fP, then the number
created connections equals to the cross product \fIn * m\fP\&.
.SS disconnect
.PP
Synopsis:
.IP
\fIdisconnect\fP \fIA\fP \fIB\fP
.PP
Removes a previously established connection between \fIA\fP and \fIB\fP\&.
.PP
As in \fB\fCconnect\fR, Both \fIA\fP and \fIB\fP can consist of a comma\-separated lists of
actor labels.
.SS import
.PP
Synopsis:
.IP
\fIimport\fP \fIformat\fP [\fIspawn\-arguments\fP]
.PP
Imports data on standard input and send it to locally running node. This
command is a shorthand for spawning a source, connecting it with an importer,
and associating standard input of the process invoking \fIimport\fP with the input
stream of the spawned source.
.PP
Because \fIimport\fP always reads from standard input, \fI\-r file\fP has no effect.
.SS export
.PP
Synopsis:
.IP
\fIexport\fP [\fIarguments\fP] \fIexpression\fP
.PP
Issues a query and exports results to standard output. This command is a
shorthand for spawning a exporter and sink, linking the two, and relaying the
resulting event stream arriving at the sink to standard output of the process
invoking \fIexport\fP\&.
.PP
Because \fIexport\fP always writes to standard output, \fI\-w file\fP has no effect.
.SH EXAMPLES
.PP
Start a node at 10.0.0.1 on port 42000 with debug log verbosity in the foreground:
.PP
.RS
.nf
vast \-e 10.0.0.1:42000 \-l 5 start \-f
.fi
.RE
.PP
Send Bro
\[la]http://www.bro.org\[ra] logs to the remote node:
.PP
.RS
.nf
zcat *.log.gz | vast \-e 10.0.0.1:42000 import bro
.fi
.RE
.PP
Import a PCAP trace into a local VAST node in one shot:
.PP
.RS
.nf
vast import pcap < trace.pcap
.fi
.RE
.PP
Query a local node and get the result back as PCAP trace:
.PP
.RS
.nf
vast export pcap \-h "sport > 60000/tcp && src !in 10.0.0.0/8" \\
  | ipsumdump \-\-collate \-w \- \\
  | tcpdump \-r \- \-nl
.fi
.RE
.PP
Make the node at 10.0.0.1 peer with 10.0.0.2:
.PP
.RS
.nf
vast \-e 10.0.0.1 peer 10.0.0.2
.fi
.RE
.PP
Connect to a node running at 1.2.3.4 on port 31337 and show the
topology:
.PP
.RS
.nf
vast \-e 1.2.3.4:31337 show topology
.fi
.RE
.PP
Run a historical query, printed in ASCII, limited to at most 10 results:
.PP
.RS
.nf
vast export ascii \-h \-e 10 :addr in 10.0.0.0/8
.fi
.RE
.SH ISSUES
.PP
If you encounter a bug or have suggestions for improvement, please file an
issue at 
\[la]http://vast.fail\[ra]\&.
.SH SEE ALSO
.PP
Visit 
\[la]https://github.com/mavam/vast\[ra] for more information about VAST.
