#! /usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

docker compose -f $SCRIPT_DIR/../../../docker-compose.yaml \
    run \
    --entrypoint vast/search.py \
    --volume $SCRIPT_DIR:/job \
    --interactive=false \
    --no-TTY \
    neuron \
    /job

EXPECTED_OUTPUT_FILE=$SCRIPT_DIR/output/output.json
if [ ! -f "$EXPECTED_OUTPUT_FILE" ]; then
    echo "$EXPECTED_OUTPUT_FILE not found"
    exit 1
fi
