#! /usr/bin/env bash

set -e

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
EXPECTED_OUTPUT_FILE=$SCRIPT_DIR/output/output.json
PROJECT_DIRECTORY="--project-directory $SCRIPT_DIR/../../../"

COMPOSE_FILES="-f docker-compose.yaml"
if [[ "$1" == "service" ]]; then
  COMPOSE_FILES=" -f ../vast/docker-compose.yaml ${COMPOSE_FILES} -f docker-compose.vast.yaml"
elif [[ "$1" == "host" ]]; then
  COMPOSE_FILES=$COMPOSE_FILES
else
  echo "Missing argument service|host"
  exit 1
fi

# Cleanup before
rm -f EXPECTED_OUTPUT_FILE
docker compose $PROJECT_DIRECTORY \
  $COMPOSE_FILES \
  down -v

docker compose $PROJECT_DIRECTORY \
  $COMPOSE_FILES \
  run \
  --entrypoint vast/search.py \
  --volume $SCRIPT_DIR/input/$1.json:/job/input/input.json \
  --volume $SCRIPT_DIR/output:/job/output \
  --interactive=false \
  --no-TTY \
  --rm \
  neuron \
  /job \
  || true

# Cleanup after
docker compose $PROJECT_DIRECTORY \
  $COMPOSE_FILES \
  down -v

grep -q "\"success\": true" $EXPECTED_OUTPUT_FILE || \
  (echo "Neuron execution failed" && exit 1)
