//    _   _____   __________
//   | | / / _ | / __/_  __/     Visibility
//   | |/ / __ |_\ \  / /          Across
//   |___/_/ |_/___/ /_/       Space and Time
//
// SPDX-FileCopyrightText: (c) 2018 The Tenzir Contributors
// SPDX-License-Identifier: BSD-3-Clause

#pragma once

#include "tenzir/command.hpp"

#include <memory>
#include <string_view>
#include <utility>

namespace tenzir {

/// Creates the applications command tree based on a single root command.
/// @returns the root command.
std::pair<std::unique_ptr<tenzir::command>, tenzir::command::factory>
make_application(std::string_view path);

/// Formats a useful human readable error message on the output stream.
/// @param root The root command of the application.
/// @param err An error generated by the application.
/// @param os The output stream to write to.
void render_error(const command& root, const caf::error& err, std::ostream& os);

/// @returns default options for commands.
command::opts_builder opts(std::string_view category);

} // namespace tenzir
