global(workDirectory="/tmp/rsyslog")

module(load="imtcp")
module(load="omrelp")

template(name="relp_raw" type="string" string="%rawmsg%")

ruleset(name="forward_relp") {
  action(
    type="omrelp"
    target="host.docker.internal"
    port="2514"
    template="relp_raw"
    windowSize="1024"
    action.resumeRetryCount="-1"
    queue.type="LinkedList"
    queue.size="1000000"
  )
}

input(type="imtcp" port="1514" ruleset="forward_relp")
