#!/bin/sh

# A script to build the entire VAST ci pipeline inside a Debian container.

# Execute this script from the toplevel directory: `vast~:   .ci/debian/build-local`
# You can pass an optional branch name as argument: `vast~: .ci/debian/build-local story/ch1234`

IMAGE=tenzir-vast-local-ci-debian:latest
docker build -f .ci/debian/Dockerfile . -t "$IMAGE"

BRANCH="${1:-master}"

docker run --rm -t "$IMAGE" sh -c "git clone --branch=$BRANCH https://github.com/tenzir/vast.git &&
  cd vast &&
  sh .ci/scripts/run-all-targets"
