#!/bin/sh


# A script to builds the entire VAST ci pipeline locally on macOS. That includes an install, so be careful.

unset CPPFLAGS CFLAGS CXXFLAGS LDFLAGS ARFLAGS
export CC=cc
export CXX=c++

if ! command -v greadlink >/dev/null 2>&1; then
  >&2 echo "Cannot find greadlink, please install coreutils"
  exit 1
fi

export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

CI_FOLDER="$(dirname "$(dirname "$(readlink -f "$0")")")"

sh "$CI_FOLDER/scripts/run-all-targets"
