#!/usr/bin/env python3
"""Generate the Sigma OCSF mapping catalog as JSON for documentation.

Reads the YAML mapping documents under
`libtenzir/builtins/operators/sigma/catalog/` and emits one structured JSON
document that the documentation website renders with the
`SigmaMappingCatalog` component family.

Usage:
    scripts/generate-sigma-ocsf-catalog.py [-o OUTPUT]

Without `-o`, the JSON goes to stdout.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("error: PyYAML is required (pip install pyyaml)")

CATALOG_DIR = (
    Path(__file__).resolve().parent.parent
    / "libtenzir/builtins/operators/sigma/catalog"
)

CLASSES_INC = (
    Path(__file__).resolve().parent.parent / "libtenzir/include/tenzir/ocsf_classes.inc"
)


def load_class_names() -> dict[int, str]:
    """Reads OCSF class names from the generated engine table.

    Entries look like `X(v1_9_0, 1007, "Process Activity")`. Later versions
    overwrite earlier ones, so the newest schema wins for renamed classes.
    """
    result: dict[int, str] = {}
    pattern = re.compile(r'^X\((v\d+_\d+_\d+(?:_dev)?), (\d+), "([^"]+)"\)')
    for line in CLASSES_INC.read_text().splitlines():
        if match := pattern.match(line):
            result[int(match.group(2))] = match.group(3)
    return result


CLASS_NAMES = load_class_names()


def load_documents() -> list[str]:
    paths = sorted(CATALOG_DIR.rglob("*.yaml"))
    if not paths:
        sys.exit(f"error: no YAML documents found in {CATALOG_DIR}")
    return [path.read_text() for path in paths]


def structure_field(name: str, spec: dict) -> dict:
    result = {
        "sigma_field": name,
        "primitive": spec["primitive"],
        "params": {
            key: value
            for key, value in spec.items()
            if key
            not in (
                "primitive",
                "kind",
                "rule-value",
                "notes",
                "provenance-scoped",
            )
        },
        "kind": spec.get("kind", "any"),
        "notes": spec.get("notes", ""),
        "provenance_scoped": spec.get("provenance-scoped", False),
    }
    rule_value = spec.get("rule-value", "identity")
    if isinstance(rule_value, str):
        result["rule_value"] = {"type": rule_value}
    else:
        dictionary = rule_value["dictionary"]
        result["rule_value"] = {
            "type": "dictionary",
            "name": dictionary["name"],
            "entries": dictionary["entries"],
        }
    return result


OS_PRODUCTS = ("windows", "linux", "macos")


def structure_mapping(document: dict) -> dict:
    guard = document["guard"]
    class_uid = guard["class-uid"]
    product = document["logsource"]["product"]
    return {
        "id": document["id"],
        "title": document["title"],
        "selector": {
            "category": document["logsource"].get("category"),
            "product": document["logsource"]["product"],
            "service": document["logsource"].get("service"),
            "optional_service": document["logsource"].get("optional-service", False),
        },
        "class_uid": class_uid,
        "class_name": CLASS_NAMES.get(class_uid),
        "guard": {
            "activities": guard["activities"],
            # Derived, not declared: an OS product implies an OS guard.
            "os": product if product in OS_PRODUCTS else None,
            "source": guard.get("source"),
            "log_name": guard.get("log-name"),
            "conflicting_log_names": guard.get("conflicting-log-names", []),
        },
        "fields": [
            structure_field(name, spec) for name, spec in document["fields"].items()
        ],
        "unmapped": document.get("unmapped", []),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--output", type=Path, help="output JSON file")
    args = parser.parse_args()
    families = [
        structure_mapping(yaml.safe_load(document)) for document in load_documents()
    ]
    result = {
        "$comment": "Generated by engine/scripts/generate-sigma-ocsf-catalog.py"
        " from libtenzir/builtins/operators/sigma/catalog/*.yaml."
        " Do not edit manually.",
        "families": families,
    }
    output = json.dumps(result, indent=2) + "\n"
    if args.output:
        args.output.write_text(output)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
