#!/usr/bin/env python3

"""Generate the built-in IPFIX Information Element registry."""

from __future__ import annotations

import argparse
import csv
import io
import pathlib
import re
import urllib.request


DEFAULT_SOURCE = "https://www.iana.org/assignments/ipfix/ipfix-information-elements.csv"
DEFAULT_OUTPUT = pathlib.Path("libtenzir/src/netflow/iana.hpp")
SUPPORTED_TYPES = {
    "octet_array",
    "unsigned8",
    "unsigned16",
    "unsigned32",
    "unsigned64",
    "signed8",
    "signed16",
    "signed32",
    "signed64",
    "float32",
    "float64",
    "boolean",
    "mac_address",
    "string",
    "date_time_seconds",
    "date_time_milliseconds",
    "date_time_microseconds",
    "date_time_nanoseconds",
    "ipv4_address",
    "ipv6_address",
    "basic_list",
    "sub_template_list",
    "sub_template_multi_list",
}


def camel_to_snake(name: str) -> str:
    result = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    result = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", result).lower()
    return result.replace("i_pv", "ipv")


def read_rows(source: str) -> list[tuple[int, str, str]]:
    with urllib.request.urlopen(source) as response:
        text = response.read().decode("utf-8-sig")
    result: list[tuple[int, str, str]] = []
    for row in csv.DictReader(io.StringIO(text)):
        element_id = row["ElementID"]
        name = row["Name"]
        data_type = row["Abstract Data Type"]
        if not element_id.isdigit() or not name or not data_type:
            continue
        normalized_type = camel_to_snake(data_type)
        if normalized_type not in SUPPORTED_TYPES:
            normalized_type = "octet_array"
        result.append((int(element_id), camel_to_snake(name), normalized_type))
    result.sort()
    return result


def render(rows: list[tuple[int, str, str]], source: str) -> str:
    entries = "\n".join(
        f'  InformationElement{{{element_id}, "{name}", '
        f"InformationElementType::{data_type}}},"
        for element_id, name, data_type in rows
    )
    return f"""//
//  ▀▀█▀▀ █▀▀▀ █▄  █ ▀▀▀█▀ ▀█▀ █▀▀▄
//    █   █▀▀  █ ▀▄█  ▄▀    █  █▀▀▄
//    ▀   ▀▀▀▀ ▀   ▀ ▀▀▀▀▀ ▀▀▀ ▀  ▀
//
// SPDX-FileCopyrightText: (c) 2026 The Tenzir Contributors
// SPDX-License-Identifier: BSD-3-Clause

// Generated by scripts/generate-netflow-iana.py from:
// {source}

#pragma once

#include "tenzir/detail/inspection_common.hpp"

#include <array>
#include <cstdint>
#include <string_view>

namespace tenzir::netflow::detail {{

enum class InformationElementType : uint8_t {{
  octet_array,
  unsigned8,
  unsigned16,
  unsigned32,
  unsigned64,
  signed8,
  signed16,
  signed32,
  signed64,
  float32,
  float64,
  boolean,
  mac_address,
  string,
  date_time_seconds,
  date_time_milliseconds,
  date_time_microseconds,
  date_time_nanoseconds,
  ipv4_address,
  ipv6_address,
  basic_list,
  sub_template_list,
  sub_template_multi_list,
}};

template <class Inspector>
auto inspect(Inspector& f, InformationElementType& x) -> bool {{
  return tenzir::detail::inspect_enum(f, x);
}}

struct InformationElement {{
  uint16_t id;
  std::string_view name;
  InformationElementType type;
}};

inline constexpr auto information_elements
  = std::array<InformationElement, {len(rows)}>{{{{
{entries}
}}}};

}} // namespace tenzir::netflow::detail
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()
    rows = read_rows(args.source)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render(rows, args.source))


if __name__ == "__main__":
    main()
