#!/usr/bin/env python3

import sys
import subprocess
import socket
import os
from pathlib import Path

PORT = int(os.environ["TENZIR_TESTER_CHECK_PORT"])
UPDATE = bool(int(os.environ["TENZIR_TESTER_CHECK_UPDATE"]))
PATH = Path(os.environ["TENZIR_TESTER_CHECK_PATH"])

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect(("127.0.0.1", PORT))
step = int(s.recv(1024))
s.close()

inv = sys.argv[1:]
expected_code = 0
if inv[0] == "!":
    inv = inv[1:]
    expected_code = 1

p = subprocess.run(inv, stdout=subprocess.PIPE)
# TODO: What about stderr?
if p.returncode != expected_code:
    sys.exit(1)
ref_path = PATH.with_suffix(f".{step}.txt")
if UPDATE:
    # TODO: Maybe always write to temporary directory and check outside?
    with ref_path.open("wb") as f:
        f.write(p.stdout)
    sys.exit(0)
try:
    ref = ref_path.read_bytes()
    if ref != p.stdout:
        # TODO: Diff.
        sys.exit(f"mismatch in stdout in step {step} (TODO: diff here)")
except FileNotFoundError:
    sys.exit(f"reference file for step {step} does not exit")
