#! /usr/bin/env bash
set -eux -o pipefail

pushd "$(git -C "$(dirname "$(readlink -f "${0}")")" rev-parse --show-toplevel)/docker"

# Setup cleanup
function down {
  exit_code=$?
  docker compose logs
  docker compose down -v
  popd
  exit $exit_code
}
trap down EXIT

# Start thehive without the app
export COMPOSE_FILE
COMPOSE_FILE="compose/thehive.yaml"
COMPOSE_FILE="$COMPOSE_FILE:compose/thehive.vast.yaml"
COMPOSE_FILE="$COMPOSE_FILE:compose/vast.yaml"
docker compose up --build -d

sleep 3

# import an alert before starting the app
docker compose run --rm --no-TTY vast import --blocking suricata \
    < ../vast/integration/data/suricata/eve.json

# add the app to the stack
COMPOSE_FILE="$COMPOSE_FILE:compose/thehive.app.yaml"
docker compose up --build --no-recreate -d thehive-app

# check that the historical import took place
docker compose run --rm --no-deps thehive-app app-thehive-count-alerts 2>&1 | \
    tee /dev/stderr | \
    grep -q "alert_count=1"

# import both a duplicate and a new alert
cat ../vast/integration/data/suricata/eve.json | \
    docker compose run --rm --no-TTY vast import --blocking suricata
cat ../vast/integration/data/suricata/eve.json | \
    sed -e 's/2011-08-12/2011-08-13/g' | \
    docker compose run --rm --no-TTY vast import --blocking suricata

# check that the continuous import took place, but not for the duplicate
docker compose run --rm --no-deps thehive-app app-thehive-count-alerts 2>&1 | \
    tee /dev/stderr | \
    grep -q "alert_count=2"
