#!/bin/sh
#
# This script bulk-loads VAST with a directory of Bro logs.

# Defaults
logs='{conn,dns,ftp,http,irc,smtp,ssh,tunnel}'
receiver=127.0.0.1
verbosity=3

usage()
{
    printf "usage: %s <options> <log_dir>\n" $(basename $0)
    echo ''
    echo 'log_dir: directory with Bro logs'
    echo ''
    echo 'options:'
    echo '    -d <vast>   VAST directory'
    echo "    -l <logs>   logs to ingest [$logs]"
    echo "    -p <part>   partition name [defautls to log_dir]"
    echo "    -r <remote> VAST receiver address [$receiver]"
    echo "    -v <level>  VAST console verbosity [$verbosity]"
    echo '    -h|-?       display this help'
    echo ''
}

while getopts "d:hl:p:r:v:?" opt ; do
  case "$opt" in
    d)
      vast_dir=$OPTARG
      ;;
    l)
      logs=$OPTARG
      ;;
    r)
      receiver=$OPTARG
      ;;
    v)
      verbosity=$OPTARG
      ;;
    h|\?)
      usage
      exit 0
    ;;
  esac
done

shift $(expr $OPTIND - 1)
log_dir=$1

if [ -z "$partition" ]; then
  partition=$(basename $log_dir)
fi

if [ -z "$log_dir" ]; then
  usage
  exit 1
elif [ ! -d "$log_dir" ]; then
  echo "no such directory: $log_dir" > /dev/stderr
  exit 1
fi

if ! which vast > /dev/null 2>&1; then
  echo "could not find vast executable in path" > /dev/stderr
  exit 1
fi

if [ ! -d $vast_dir ]; then
  echo "directory does not exist: $vast_dir" > /dev/stderr
  exit 1
fi

for file in $(eval ls "$log_dir/$logs.log" 2> /dev/null); do
  vast -v $verbosity -d $vast_dir -I -R -A -X -T \
    --receiver.host $receiver \
    --archive.max-segments 1 \
    --index.partition $partition \
    --ingest.file-name $file \
    --ingest.time-field 0
done
