#!/bin/bash
#
# This script install the necessary dependencies in order for VAST to run in
# the Travis CI environment.

# Add extra repositories for GCC and Boost
sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ quantal main universe"
sudo apt-get update -qq

# Boost
sudo apt-get install -qq libboost1.50-all-dev

# When building with GCC, update to 4.7.
if [[ $CXX == "g++" ]] ; then
    sudo apt-get install -qq g++-4.7
    export CXX=g++-4.7
    export CC=gcc-4.7
elif [[ $CXX == "clang++" ]] ; then
    echo "TODO: setup clang 3.2"
    exit 1
fi

# The prefix where we install our dependencies in.
export PREFIX=$HOME/builds/mavam/prefix

# Libcppa
git clone git://github.com/Neverlord/libcppa.git
cd libcppa
./configure --enable-debug --prefix=$PREFIX
make install
cd ..

# 0event
git clone git://github.com/mavam/ze.git
cd ze
./configure --enable-debug --prefix=$PREFIX
make install
cd ..

# VAST
./configure --enable-debug --with-libcppa=$PREFIX --with-0event=$PREFIX
