#!/bin/bash
# This script install the necessary dependencies in order for VAST to run in
# the Travis CI environment.

# Boost
sudo apt-get install libboost1.50-all-dev

# When building with GCC, update to 4.7.
if [[ "$CXX" == "g++" ]] ; then
    echo downloading GCC 4.7
    echo "\n" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    sudo apt-get update
    sudo apt-get install g++-4.7
    export CXX=g++-4.7
    export CC=gcc-4.7
elif [[ "$CXX" == "clang++" ]] ; then
fi

# The prefix where we install our dependencies in.
export PREFIX=$HOME/builds/mavam/prefix

# Libcppa
git clone git://github.com/Neverlord/libcppa.git
cd libcppa
./configure --enable-debug --prefix=$PREFIX
make install
cd ..

# 0event
git clone git://github.com/mavam/ze.git
cd ze
./configure --enable-debug --prefix=$PREFIX
make install
cd ..
