# Embeds the declarative Sigma OCSF mapping catalog into a generated
# translation unit. Each YAML document under INPUT_DIR becomes one embedded
# string; the sigma builtin parses them at startup.
#
# Usage:
#   cmake -DINPUT_DIR=<dir> -DOUTPUT=<file> -P TenzirEmbedSigmaCatalog.cmake

if (NOT INPUT_DIR OR NOT OUTPUT)
  message(FATAL_ERROR "INPUT_DIR and OUTPUT are required")
endif ()

file(GLOB_RECURSE documents "${INPUT_DIR}/*.yaml")
list(SORT documents)

set(entries "")
foreach (document IN LISTS documents)
  file(READ "${document}" content)
  if (content MATCHES "\\)tnz_catalog\"")
    message(FATAL_ERROR "${document} contains the raw string delimiter")
  endif ()
  string(APPEND entries "  R\"tnz_catalog(${content})tnz_catalog\",\n")
endforeach ()
list(LENGTH documents count)

string(
  CONCAT
    generated
    "// Generated by cmake/TenzirEmbedSigmaCatalog.cmake from\n"
    "// builtins/operators/sigma/catalog/*.yaml -- do not edit.\n"
    "\n"
    "#include <array>\n"
    "#include <span>\n"
    "#include <string_view>\n"
    "\n"
    "namespace tenzir::plugins::sigma::ocsf::generated {\n"
    "\n"
    "namespace {\n"
    "\n"
    "constexpr auto documents = std::array<std::string_view, ${count}>{\n"
    "${entries}"
    "};\n"
    "\n"
    "} // namespace\n"
    "\n"
    "auto embedded_catalog_documents() -> std::span<std::string_view const> {\n"
    "  return documents;\n"
    "}\n"
    "\n"
    "} // namespace tenzir::plugins::sigma::ocsf::generated\n")

file(WRITE "${OUTPUT}.tmp" "${generated}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${OUTPUT}.tmp"
                        "${OUTPUT}")
file(REMOVE "${OUTPUT}.tmp")
