#!/bin/sh

set -ex

. "$(dirname "$0")"/initialize-env
"$(dirname "$0")"/submodule-update

for target in all test integration install package; do
  TARGET="$target" "$(dirname "$(readlink -f "$0")")/build-target"
done
