#!/bin/sh

. .ci/scripts/initialize-env

TARGET=all .ci/scripts/build-target
TARGET=test .ci/scripts/build-target
TARGET=integration .ci/scripts/build-target
TARGET=install .ci/scripts/build-target
TARGET=package .ci/scripts/build-target
