#!/bin/sh

# error on unset variables
set -u

# this script expects a file called `mule_ssh_key` to be present in the current working directory.

if ! stat mule_ssh_key; then
  echo "Cannot find mule-ssh key."
  exit 1
fi

while ! rsync --rsh "ssh -i mule_ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
    --archive --compress --progress --partial "$1" "$2" ; do
  sleep 15
  echo "Warning: rsync failure. Retrying ..."
done
