name: Validate Changelog

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - "changelog/**"
      - ".github/workflows/changelog-validate.yaml"
      - "lefthook.yml"
  merge_group:
    types:
      - checks_requested
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    name: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          version: "0.9.2"

      - name: Validate changelog
        run: uvx tenzir-ship validate
