name: Cleanup Docs Preview

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup-docs-preview:
    name: Clean up Docs Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Remove preview from Surge
        run: |
          npm install -g surge
          surge teardown https://tenzir-tenzir-preview-${{ github.event.pull_request.number }}.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        continue-on-error: true

      - name: Update comment - Cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER="${{ github.event.pull_request.number }}"

          # Function to update docs preview section
          update_docs_section() {
            local existing_comment="$1"
            local docs_content="$2"

            # Replace the docs preview section
            local updated_comment=$(echo "$existing_comment" | sed '/## 📚 Documentation Preview/,$d')
            echo "$updated_comment

          ## 📚 Documentation Preview

          $docs_content"
          }

          # Get existing comment
          EXISTING_COMMENT=$(gh api repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            --jq '.[] | select(.body | startswith("<!-- add-changelog-entry -->")) | .body' | head -1 || echo "")

          if [ -n "$EXISTING_COMMENT" ]; then
            DOCS_CLEANUP_CONTENT="🧹 **Preview deployment has been cleaned up**

          The documentation preview for this PR has been removed since the PR was closed."

            UPDATED_COMMENT=$(update_docs_section "$EXISTING_COMMENT" "$DOCS_CLEANUP_CONTENT")

            COMMENT_ID=$(gh api repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
              --jq '.[] | select(.body | startswith("<!-- add-changelog-entry -->")) | .id' | head -1)

            if [ -n "$COMMENT_ID" ]; then
              gh api repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
                -X PATCH \
                -f body="$UPDATED_COMMENT"
            fi
          fi
