name: "Jupyter Notebook"
on:
  push:
    paths:
    - 'examples/jupyter'
    - '.github/workflows/jupyter.yaml'
  release:
    types: published
env:
  DEBIAN_FRONTEND: noninteractive
jobs:
  test-demo:
    name: Jupyter Test
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Install Dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get -qqy install ca-certificates libpcap-dev libssl-dev lsb-release wget
        # Install Apache Arrow (c.f. https://arrow.apache.org/install/)
        wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt-get -y install ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo sed -i'' -e 's,https://apache.bintray.com/,https://apache.jfrog.io/artifactory/,g' /etc/apt/sources.list.d/apache-arrow.sources
        sudo apt-get update
        sudo apt-get -y install libarrow-dev

    # Fetch latest successful build of the 'VAST' workflow, master branch
    - name: Fetch VAST
      run: |
        curl -L -O https://storage.googleapis.com/tenzir-public-data/vast-static-builds/vast-static-latest.tar.gz
        tar xfz vast-static-latest.tar.gz
        sudo ln -sf "$PWD/bin/vast" /usr/bin/vast

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PyVAST and Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install wheel setuptools
        python -m pip install pyvast
        python -m pip install -r examples/jupyter/requirements.txt

    - name: Fetch Demo Data
      run: |
        curl -L -o vast-jupyter-demo.tgz https://storage.googleapis.com/tenzir-public-data/vast-jupyter-demo.tgz
        tar xzf vast-jupyter-demo.tgz

    - name: Run Demo
      run: |
        set -x
        export PATH="$PWD"/vast/bin:"$PATH"
        nohup vast start &
        while ! lsof -i ":42000"; do sleep 1; done
        vast import -r vast-jupyter-demo/M57-day11-18-conn.log zeek
        vast import -r vast-jupyter-demo/M57-day11-18.json suricata
        vast import -r vast-jupyter-demo/M57-2009-day11-18.trace pcap
        jupyter-nbconvert --to notebook --execute --output vast-example-1.py examples/jupyter/vast-example-1.ipynb
        vast stop
