// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    {
      type: 'doc',
      id: 'overview',
    },
    {
      type: 'doc',
      id: 'faqs',
    },
    {
      type: 'html',
      value: '<br><b>Tutorials<b/>',
    },
    {
      type: 'doc',
      id: 'tutorials/quickstart/README',
    },
    {
      type: 'doc',
      id: 'tutorials/map-data-to-ocsf/README',
    },
    {
      type: 'doc',
      id: 'tutorials/write-a-package',
    },
    {
      type: 'html',
      value: '<br><b>Guides<b/>',
    },
    {
      type: 'category',
      label: 'Installation',
      link: {
        type: 'doc',
        id: 'installation'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'installation',
      }],
    },
    {
      type: 'category',
      label: 'Usage',
      link: {
        type: 'doc',
        id: 'usage'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'usage',
      }],
    },
    {
      type: 'category',
      label: 'Integrations',
      link: {
        type: 'doc',
        id: 'integrations'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'integrations',
      }],
    },
    {
      type: 'category',
      label: 'Contribution',
      link: {
        type: 'doc',
        id: 'contribution'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'contribution',
      }],
    },
    {
      type: 'category',
      label: 'Development',
      link: {
        type: 'doc',
        id: 'development'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'development',
      }],
    },
    {
      type: 'doc',
      id: 'troubleshooting',
    },
    {
      type: 'doc',
      id: 'tql2-migration',
    },
    {
      type: 'html',
      value: '<br><b>Reference<b/>',
    },
    {
      type: 'category',
      label: 'Language',
      items: [{
        type: 'autogenerated',
        dirName: 'tql2/language',
      }],
    },
    // {
    //   type: 'doc',
    //   id: 'tql2/operators',
    // },
    {
      type: 'category',
      label: 'Operators',
      link: {
        type: 'doc',
        id: 'tql2/operators'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'tql2/operators',
      }],
    },
    {
      type: 'category',
      label: 'Functions',
      link: {
        type: 'doc',
        id: 'tql2/functions'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'tql2/functions',
      }],
    },
    {
      type: 'doc',
      id: 'configuration',
    },
    {
      type: 'doc',
      id: 'rest-api',
    },
    {
      type: 'doc',
      id: 'python-library',
    },
    {
      type: 'doc',
      id: 'platform-cli',
    },
    {
      type: 'doc',
      id: 'glossary',
    },
    {
      type: 'html',
      value: '<br><b>Previous Reference<b/>',
    },
    {
      type: 'category',
      label: 'Language',
      link: {
        type: 'doc',
        id: 'language'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'language',
      }],
    },
    {
      type: 'category',
      label: 'Operators',
      link: {
        type: 'doc',
        id: 'operators'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'operators',
      }],
    },
    {
      type: 'category',
      label: 'Connectors',
      link: {
        type: 'doc',
        id: 'connectors'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'connectors',
      }],
    },
    {
      type: 'category',
      label: 'Formats',
      link: {
        type: 'doc',
        id: 'formats'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'formats',
      }],
    },
    {
      type: 'category',
      label: 'Contexts',
      link: {
        type: 'doc',
        id: 'contexts'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'contexts',
      }],
    },
    {
      type: 'category',
      label: 'Data Model',
      link: {
        type: 'doc',
        id: 'data-model'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'data-model',
      }],
    },
    {
      type: 'html',
      value: '<br><b>Explanation<b/>',
    },
    {
      type: 'doc',
      id: 'pipelines',
    },
    {
      type: 'doc',
      id: 'packages',
    },
    {
      type: 'doc',
      id: 'why-tenzir',
    },
    {
      type: 'doc',
      id: 'target-audience',
    },
    {
      type: 'category',
      label: 'Use Cases',
      link: {
        type: 'doc',
        id: 'use-cases'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'use-cases',
      }],
    },
    {
      type: 'category',
      label: 'Architecture',
      link: {
        type: 'doc',
        id: 'architecture'
      },
      items: [{
        type: 'autogenerated',
        dirName: 'architecture',
      }],
    },
  ],
};

module.exports = sidebars;
